## Kết quả model trả về

In [40]:
complex_test_set = [
    # --- NHÓM 1: CÔNG NGHỆ THÔNG TIN (IT & SOFTWARE) ---
    {
        "query": "Thực tập sinh IT Python Backend không yêu cầu kinh nghiệm",
        "must_have": ["thực tập", "python", "backend"],
        "min_match": 2
    },
    {
        "query": "Lập trình viên Frontend ReactJS lương cao tại Hà Nội",
        "must_have": ["frontend", "reactjs", "hà nội"],
        "min_match": 2
    },
    {
        "query": "Tuyển Mobile Developer Android iOS kinh nghiệm 1 năm",
        "must_have": ["mobile", "android", "ios"],
        "min_match": 2
    },
    {
        "query": "Chuyên viên phân tích dữ liệu Data Analyst biết SQL",
        "must_have": ["data analyst", "phân tích dữ liệu", "sql"],
        "min_match": 2
    },
    {
        "query": "Tester kiểm thử phần mềm Manual và Automation",
        "must_have": ["tester", "kiểm thử", "automation"],
        "min_match": 2
    },

    # --- NHÓM 2: KINH DOANH & BÁN HÀNG (SALES) ---
    {
        "query": "Nhân viên kinh doanh bất động sản thu nhập hấp dẫn",
        "must_have": ["kinh doanh", "bất động sản", "sale"],
        "min_match": 2
    },
    {
        "query": "Trưởng phòng kinh doanh B2B tại Hồ Chí Minh",
        "must_have": ["trưởng phòng", "kinh doanh", "hồ chí minh"],
        "min_match": 2
    },
    {
        "query": "Nhân viên tư vấn bán hàng part time",
        "must_have": ["bán hàng", "tư vấn", "part time"],
        "min_match": 2
    },
    {
        "query": "Sales Admin hỗ trợ kinh doanh biết tiếng Anh",
        "must_have": ["sales admin", "hỗ trợ", "tiếng anh"],
        "min_match": 2
    },

    # --- NHÓM 3: MARKETING & TRUYỀN THÔNG ---
    {
        "query": "Chuyên viên Digital Marketing chạy quảng cáo Facebook Ads",
        "must_have": ["digital marketing", "facebook", "ads"],
        "min_match": 2
    },
    {
        "query": "Content Writer viết bài SEO Marketing",
        "must_have": ["content", "seo", "marketing"],
        "min_match": 2
    },
    {
        "query": "Graphic Designer thiết kế đồ họa 2D biết Photoshop",
        "must_have": ["designer", "thiết kế", "photoshop"],
        "min_match": 2
    },

    # --- NHÓM 4: HÀNH CHÍNH - NHÂN SỰ - KẾ TOÁN ---
    {
        "query": "Kế toán tổng hợp có kinh nghiệm làm báo cáo thuế",
        "must_have": ["kế toán", "tổng hợp", "thuế"],
        "min_match": 2
    },
    {
        "query": "Chuyên viên tuyển dụng nhân sự marketing",
        "must_have": ["tuyển dụng", "nhân sự", "marketing"],
        "min_match": 2
    },
    {
        "query": "Nhân viên hành chính văn phòng lễ tân",
        "must_have": ["hành chính", "văn phòng", "lễ tân"],
        "min_match": 2
    },

    # --- NHÓM 5: CÁC NGÀNH NGHỀ KHÁC & ĐẶC THÙ ---
    {
        "query": "Nhân viên xuất nhập khẩu Logistics tiếng Trung",
        "must_have": ["xuất nhập khẩu", "logistics", "tiếng trung"],
        "min_match": 2
    },
    {
        "query": "Kỹ sư cơ khí chế tạo máy làm việc tại nhà máy",
        "must_have": ["kỹ sư", "cơ khí", "máy"],
        "min_match": 2
    },
    {
        "query": "Nhân viên chăm sóc khách hàng Call Center",
        "must_have": ["chăm sóc khách hàng", "call center", "tư vấn"],
        "min_match": 2
    },
    {
        "query": "Việc làm Online tại nhà Remote không cần kinh nghiệm",
        "must_have": ["online", "remote", "tại nhà"],
        "min_match": 2
    },
    {
        "query": "Phiên dịch viên tiếng Trung tại Hồ Chí Minh",
        "must_have": ["phiên dịch", "tiếng Trung", "Hồ Chí Minh"],
        "min_match": 2
    }
]

print(f"📋 Số lượng câu test: {len(complex_test_set)}")

📋 Số lượng câu test: 20

In [31]:
import requests
import pandas as pd
from tqdm.notebook import tqdm

API_URL = "http://127.0.0.1:8000/api/search"
TOP_K = 20

MODEL_MAPPING = {
    "TF-IDF": "tfidf",
    "Word2Vec": "w2v",
    "Doc2Vec": "doc2vec",
    "LaBSE": "labse", 
    "BGE-M3": "bge",
    "Paraphrase": "mpnet",
    "Ensemble": "ensemble",
    "Word2Vec_sg": "w2v_sg",
    "Doc2Vec_dbow": "doc2vec_dbow",
}

TYPE_TO_SEARCH_MODE = {
    "basic": "title",    
    "upgrade": "overall" 
}

MODELS_CONFIG = [
    {"name": "TF-IDF",      "type": "basic"},   {"name": "TF-IDF",      "type": "upgrade"},
    {"name": "Word2Vec",    "type": "basic"},   {"name": "Word2Vec",    "type": "upgrade"},
    {"name": "Word2Vec_sg",    "type": "basic"},   {"name": "Word2Vec_sg",    "type": "upgrade"},
    {"name": "Doc2Vec",     "type": "basic"},   {"name": "Doc2Vec",     "type": "upgrade"},
    {"name": "Doc2Vec_dbow",     "type": "basic"},   {"name": "Doc2Vec_dbow",     "type": "upgrade"},
    {"name": "LaBSE",       "type": "basic"},   {"name": "LaBSE",       "type": "upgrade"},
    {"name": "BGE-M3",      "type": "basic"},   {"name": "BGE-M3",      "type": "upgrade"},
    {"name": "Paraphrase",  "type": "basic"},   {"name": "Paraphrase",  "type": "upgrade"},
    {"name": "Ensemble",    "type": "basic"},   {"name": "Ensemble",    "type": "upgrade"},
]

results_log = []


for config in MODELS_CONFIG:
    raw_name = config['name']  
    m_type = config['type']    
    
    # Lấy mã định danh API 
    model_short = MODEL_MAPPING.get(raw_name, raw_name.lower())
    
    # Xác định search_type
    search_mode = TYPE_TO_SEARCH_MODE.get(m_type, "overall")
    
    display_name = f"{model_short} ({search_mode})"
    
    # --- CHẠY TẬP TEST ---
    for q_idx, test_case in enumerate(tqdm(complex_test_set, desc=display_name, leave=False)):
        query_text = test_case['query']
        
        # Payload gửi đi
        payload = {
            "query": query_text,
            "model_name": model_short,  
            "search_type": search_mode,    
            "filters": {}
        }
        
        try:
            response = requests.post(API_URL, json=payload)
            
            if response.status_code == 200:
                predictions = response.json()
                
                # --- XỬ LÝ KẾT QUẢ ---
                if isinstance(predictions, list):
                    for rank, item in enumerate(predictions):
                        if rank >= TOP_K: break
                        
                        # Chỉ lấy các trường cần thiết
                        results_log.append({
                            "model_short": model_short, # Tên model ngắn (w2v, ensemble...)
                            "model_type": m_type,       # basic/upgrade
                            "query_id": q_idx,          # ID câu query
                            "query_text": query_text,   # Nội dung câu query
                            "rank": rank + 1,           # Thứ hạng
                            "job_id": item.get('id'),   # ID job
                            "score": item.get('similarity_score', item.get('score', 0)), 
                            "label": ""                 
                        })
            else:
                if q_idx == 0: 
                    print(f"❌ Backend lỗi {display_name}: {response.status_code}")
                
        except Exception as e:
            print(f"⚠️ Lỗi kết nối: {e}")

print("🎉 DONE! Đã thu thập xong.")

# --- LƯU FILE  ---
OUTPUT_FILE = "thucong.xlsx"
df_results = pd.DataFrame(results_log)

if not df_results.empty:
    final_columns = ["model_short", "model_type", "query_id", "query_text", "rank", "job_id", "score", "label"]
    df_results = df_results[final_columns]
    
    df_results.to_excel(OUTPUT_FILE)
    print(f" Đã lưu file: {OUTPUT_FILE}")
    print(" Hãy mở file này bằng Excel để bắt đầu gán nhãn cột 'label'.")
    display(df_results.head())
else:
    print("Không thu thập được dữ liệu nào.")

tfidf (title):   0%|          | 0/20 [00:00<?, ?it/s]

tfidf (overall):   0%|          | 0/20 [00:00<?, ?it/s]

w2v (title):   0%|          | 0/20 [00:00<?, ?it/s]

w2v (overall):   0%|          | 0/20 [00:00<?, ?it/s]

w2v_sg (title):   0%|          | 0/20 [00:00<?, ?it/s]

w2v_sg (overall):   0%|          | 0/20 [00:00<?, ?it/s]

doc2vec (title):   0%|          | 0/20 [00:00<?, ?it/s]

doc2vec (overall):   0%|          | 0/20 [00:00<?, ?it/s]

doc2vec_dbow (title):   0%|          | 0/20 [00:00<?, ?it/s]

doc2vec_dbow (overall):   0%|          | 0/20 [00:00<?, ?it/s]

labse (title):   0%|          | 0/20 [00:00<?, ?it/s]

labse (overall):   0%|          | 0/20 [00:00<?, ?it/s]

bge (title):   0%|          | 0/20 [00:00<?, ?it/s]

bge (overall):   0%|          | 0/20 [00:00<?, ?it/s]

mpnet (title):   0%|          | 0/20 [00:00<?, ?it/s]

mpnet (overall):   0%|          | 0/20 [00:00<?, ?it/s]

ensemble (title):   0%|          | 0/20 [00:00<?, ?it/s]

ensemble (overall):   0%|          | 0/20 [00:00<?, ?it/s]

🎉 DONE! Đã thu thập xong.
 Đã lưu file: thucong.xlsx
 Hãy mở file này bằng Excel để bắt đầu gán nhãn cột 'label'.

,model_short,model_type,query_id,query_text,rank,job_id,score,label
0,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,1,2453,0.434380,
1,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,2,2311,0.424796,
2,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,3,2281,0.399933,
3,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,4,4571,0.331504,
4,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,5,746,0.306119,

In [32]:
data = pd.read_excel("../data/df_processed.xlsx")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6473 entries, 0 to 6472
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      6473 non-null   int64
 1   title                   6473 non-null   object
 2   description             6473 non-null   object
 3   requirements            6473 non-null   object
 4   benefit                 6473 non-null   object
 5   type                    6473 non-null   object
 6   location                6473 non-null   object
 7   position                6473 non-null   object
 8   salary_range            6473 non-null   object
 9   specializations         6473 non-null   object
 10  min_salary_edited       6473 non-null   float64
 11  max_salary_edited       6473 non-null   float64
 12  currency_salary         6473 non-null   object
 13  overall_text            6473 non-null   object
 14  title_processed         6473 non-null   object
 15  overall_text_processed  6473 non-null   object
dtypes: float64(2), int64(1), object(13)
memory usage: 809.2+ KB

In [33]:
df_merged = df_results.merge(data, left_on="job_id", right_on="id", how="left", suffixes=("", "_job"))
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model_short             7200 non-null   object
 1   model_type              7200 non-null   object
 2   query_id                7200 non-null   int64
 3   query_text              7200 non-null   object
 4   rank                    7200 non-null   int64
 5   job_id                  7200 non-null   int64
 6   score                   7200 non-null   float64
 7   label                   7200 non-null   object
 8   id                      7200 non-null   int64
 9   title                   7200 non-null   object
 10  description             7200 non-null   object
 11  requirements            7200 non-null   object
 12  benefit                 7200 non-null   object
 13  type                    7200 non-null   object
 14  location                7200 non-null   object
 15  position                7200 non-null   object
 16  salary_range            7200 non-null   object
 17  specializations         7200 non-null   object
 18  min_salary_edited       7200 non-null   float64
 19  max_salary_edited       7200 non-null   float64
 20  currency_salary         7200 non-null   object
 21  overall_text            7200 non-null   object
 22  title_processed         7200 non-null   object
 23  overall_text_processed  7200 non-null   object
dtypes: float64(3), int64(4), object(17)
memory usage: 1.3+ MB

In [35]:
df_merged.to_excel("kq.xlsx", index=False)

## Build GroundTruth

In [33]:
import pandas as pd
data = pd.read_excel("../data/df_processed.xlsx")

In [34]:
df_gt = data.copy()

In [35]:
# Tạo cột văn bản gộp  và chuyển về chữ thường
df_gt['full_text_search'] = (df_gt['title'].astype(str) + " " + 
                             df_gt['description'].astype(str)  + " " + 
                             df_gt['requirements'].astype(str) + " " +
                             df_gt['benefit'].astype(str)).str.lower()
df_gt['full_text_search'].head()

0    tuyển kế toán tổng hợp đi làm ngay thu nhập up...
1    tuyển business development executive làm việc ...
2    tuyển nhân viên content community marketing là...
3    tuyển trưởng nhóm kinh doanh làm việc tại công...
4    tuyển nhân viên kinh doanh giải pháp cntt làm ...
Name: full_text_search, dtype: object

In [36]:
complex_test_set_2 = [
    # --- NHÓM 1: CÔNG NGHỆ THÔNG TIN (IT & SOFTWARE) ---
    {
        "query": "Thực tập sinh IT Python Backend không yêu cầu kinh nghiệm",
        "must_have": ["thực tập", "python", "backend"],
        "min_match": 2
    },
    {
        "query": "Lập trình viên Frontend ReactJS lương cao tại Hà Nội",
        "must_have": ["frontend", "reactjs", "hà nội"],
        "min_match": 2
    },
    {
        "query": "Tuyển Mobile Developer Android iOS kinh nghiệm 1 năm",
        "must_have": ["mobile", "android", "ios"],
        "min_match": 2
    },
    {
        "query": "Chuyên viên phân tích dữ liệu Data Analyst biết SQL",
        "must_have": ["data analyst", "phân tích dữ liệu", "sql"],
        "min_match": 2
    },
    {
        "query": "Tester kiểm thử phần mềm Manual và Automation",
        "must_have": ["tester", "kiểm thử", "automation"],
        "min_match": 2
    },

    # --- NHÓM 2: KINH DOANH & BÁN HÀNG (SALES) ---
    {
        "query": "Nhân viên kinh doanh bất động sản thu nhập hấp dẫn",
        "must_have": ["kinh doanh", "bất động sản", "sale"],
        "min_match": 2
    },
    {
        "query": "Trưởng phòng kinh doanh B2B tại Hồ Chí Minh",
        "must_have": ["trưởng phòng", "kinh doanh", "hồ chí minh"],
        "min_match": 2
    },
    {
        "query": "Nhân viên tư vấn bán hàng part time",
        "must_have": ["bán hàng", "tư vấn", "part-time"],
        "min_match": 2
    },
    {
        "query": "Sales Admin hỗ trợ kinh doanh biết tiếng Anh",
        "must_have": ["sales admin", "hỗ trợ", "tiếng anh"],
        "min_match": 2
    },

    # --- NHÓM 3: MARKETING & TRUYỀN THÔNG ---
    {
        "query": "Chuyên viên Digital Marketing chạy quảng cáo Facebook Ads",
        "must_have": ["digital marketing", "facebook", "ads"],
        "min_match": 2
    },
    {
        "query": "Content Writer viết bài SEO Marketing",
        "must_have": ["content", "seo", "marketing"],
        "min_match": 2
    },
    {
        "query": "Graphic Designer thiết kế đồ họa 2D biết Photoshop",
        "must_have": ["designer", "thiết kế", "photoshop"],
        "min_match": 2
    },

    # --- NHÓM 4: HÀNH CHÍNH - NHÂN SỰ - KẾ TOÁN ---
    {
        "query": "Kế toán tổng hợp có kinh nghiệm làm báo cáo thuế",
        "must_have": ["kế toán", "tổng hợp", "thuế"],
        "min_match": 2
    },
    {
        "query": "Chuyên viên tuyển dụng nhân sự marketing",
        "must_have": ["tuyển dụng", "nhân sự", "marketing"],
        "min_match": 2
    },
    {
        "query": "Nhân viên hành chính văn phòng lễ tân",
        "must_have": ["hành chính", "văn phòng", "lễ tân"],
        "min_match": 2
    },

    # --- NHÓM 5: CÁC NGÀNH NGHỀ KHÁC & ĐẶC THÙ ---
    {
        "query": "Nhân viên xuất nhập khẩu Logistics tiếng Trung",
        "must_have": ["xuất nhập khẩu", "logistics", "tiếng trung"],
        "min_match": 2
    },
    {
        "query": "Kỹ sư cơ khí chế tạo máy làm việc tại nhà máy",
        "must_have": ["kỹ sư", "cơ khí", "máy"],
        "min_match": 2
    },
    {
        "query": "Nhân viên chăm sóc khách hàng Call Center",
        "must_have": ["chăm sóc khách hàng", "call center", "tư vấn"],
        "min_match": 2
    },
    {
        "query": "Việc làm Online tại nhà Remote không cần kinh nghiệm",
        "must_have": ["online", "remote", "tại nhà"],
        "min_match": 2
    },
    {
        "query": "Phiên dịch viên tiếng Trung tại Hồ Chí Minh",
        "must_have": ["phiên dịch", "tiếng Trung", "Hồ Chí Minh"],
        "min_match": 2
    }
]

print(f"📋 Số lượng câu test: {len(complex_test_set_2)}")

📋 Số lượng câu test: 20

In [37]:
# --- XÂY DỰNG GROUND TRUTH ---
from tqdm import tqdm
ground_truth_map = {} 
ground_truth_stats = [] # Để lưu thống kê xem query nào tìm được bao nhiêu job

print(f"Bắt đầu tạo Ground Truth cho {len(complex_test_set_2)} queries...")

for q_idx, test_case in enumerate(tqdm(complex_test_set_2)):
    # Lấy thông tin yêu cầu
    keywords = [k.lower() for k in test_case['must_have']]
    min_match = test_case['min_match']
    
    # --- LOGIC CỐT LÕI: ĐẾM TỪ KHÓA ---
    # Hàm này sẽ áp dụng cho từng dòng của DataFrame
    def is_relevant(text):
        if not isinstance(text, str): return False
        # Đếm số từ khóa xuất hiện trong văn bản
        match_count = sum(1 for kw in keywords if kw in text)
        return match_count >= min_match

    # Lọc ra các dòng thỏa mãn điều kiện
    relevant_jobs = df_gt[df_gt['full_text_search'].apply(is_relevant)]
    
    # Lấy tập hợp các ID
    relevant_ids = set(relevant_jobs['id'].tolist())
    
    # Lưu vào map
    ground_truth_map[q_idx] = relevant_ids
    
    # Lưu thống kê
    ground_truth_stats.append({
        "query_id": q_idx,
        "query_text": test_case['query'],
        "relevant_count": len(relevant_ids),
        "keywords": str(keywords)
    })

# --- BƯỚC 3: KIỂM TRA KẾT QUẢ ---
print("\n✅ HOÀN TẤT XÂY DỰNG GROUND TRUTH!")

Bắt đầu tạo Ground Truth cho 20 queries...

100%|██████████| 20/20 [00:00<00:00, 31.71it/s]

✅ HOÀN TẤT XÂY DỰNG GROUND TRUTH!

In [38]:
# Chuyển thống kê sang DataFrame để dễ nhìn
df_stats = pd.DataFrame(ground_truth_stats)

# Hiển thị các query tìm được ít kết quả quá (Cần cảnh báo)
low_result_queries = df_stats[df_stats['relevant_count'] < 5]
if not low_result_queries.empty:
    print(f"⚠️ CẢNH BÁO: Có {len(low_result_queries)} query có quá ít đáp án đúng (< 5 jobs).")
    print("Bạn nên nới lỏng từ khóa hoặc giảm 'min_match' cho các query này:")
    display(low_result_queries[['query_id', 'query_text', 'relevant_count', 'keywords']])
else:
    print("👍 Tất cả query đều có đủ dữ liệu để đánh giá.")

print("\nTop 5 query có nhiều đáp án đúng nhất:")
display(df_stats.sort_values('relevant_count', ascending=False).head(5))

👍 Tất cả query đều có đủ dữ liệu để đánh giá.

Top 5 query có nhiều đáp án đúng nhất:

,query_id,query_text,relevant_count,keywords
5,5,Nhân viên kinh doanh bất động sản thu nhập hấp...,885,"['kinh doanh', 'bất động sản', 'sale']"
7,7,Nhân viên tư vấn bán hàng part time,697,"['bán hàng', 'tư vấn', 'part-time']"
17,17,Nhân viên chăm sóc khách hàng Call Center,689,"['chăm sóc khách hàng', 'call center', 'tư vấn']"
8,8,Sales Admin hỗ trợ kinh doanh biết tiếng Anh,597,"['sales admin', 'hỗ trợ', 'tiếng anh']"
12,12,Kế toán tổng hợp có kinh nghiệm làm báo cáo thuế,588,"['kế toán', 'tổng hợp', 'thuế']"

In [39]:
df_stats.head(20)

,query_id,query_text,relevant_count,keywords
0,0,Thực tập sinh IT Python Backend không yêu cầu ...,43,"['thực tập', 'python', 'backend']"
1,1,Lập trình viên Frontend ReactJS lương cao tại ...,24,"['frontend', 'reactjs', 'hà nội']"
2,2,Tuyển Mobile Developer Android iOS kinh nghiệm...,86,"['mobile', 'android', 'ios']"
3,3,Chuyên viên phân tích dữ liệu Data Analyst biế...,17,"['data analyst', 'phân tích dữ liệu', 'sql']"
4,4,Tester kiểm thử phần mềm Manual và Automation,92,"['tester', 'kiểm thử', 'automation']"
5,5,Nhân viên kinh doanh bất động sản thu nhập hấp...,885,"['kinh doanh', 'bất động sản', 'sale']"
6,6,Trưởng phòng kinh doanh B2B tại Hồ Chí Minh,366,"['trưởng phòng', 'kinh doanh', 'hồ chí minh']"
7,7,Nhân viên tư vấn bán hàng part time,697,"['bán hàng', 'tư vấn', 'part-time']"
8,8,Sales Admin hỗ trợ kinh doanh biết tiếng Anh,597,"['sales admin', 'hỗ trợ', 'tiếng anh']"
9,9,Chuyên viên Digital Marketing chạy quảng cáo F...,233,"['digital marketing', 'facebook', 'ads']"
10,10,Content Writer viết bài SEO Marketing,367,"['content', 'seo', 'marketing']"
11,11,Graphic Designer thiết kế đồ họa 2D biết Photo...,451,"['designer', 'thiết kế', 'photoshop']"
12,12,Kế toán tổng hợp có kinh nghiệm làm báo cáo thuế,588,"['kế toán', 'tổng hợp', 'thuế']"
13,13,Chuyên viên tuyển dụng nhân sự marketing,551,"['tuyển dụng', 'nhân sự', 'marketing']"
14,14,Nhân viên hành chính văn phòng lễ tân,382,"['hành chính', 'văn phòng', 'lễ tân']"
15,15,Nhân viên xuất nhập khẩu Logistics tiếng Trung,54,"['xuất nhập khẩu', 'logistics', 'tiếng trung']"
16,16,Kỹ sư cơ khí chế tạo máy làm việc tại nhà máy,270,"['kỹ sư', 'cơ khí', 'máy']"
17,17,Nhân viên chăm sóc khách hàng Call Center,689,"['chăm sóc khách hàng', 'call center', 'tư vấn']"
18,18,Việc làm Online tại nhà Remote không cần kinh ...,35,"['online', 'remote', 'tại nhà']"
19,19,Phiên dịch viên tiếng Trung tại Hồ Chí Minh,44,"['phiên dịch', 'tiếng trung', 'hồ chí minh']"

In [40]:
print(ground_truth_map)

{0: {769, 770, 2307, 2308, 2311, 6408, 2443, 2197, 2453, 23, 2204, 2337, 2210, 2343, 685, 690, 6450, 6452, 5687, 6462, 2240, 2241, 716, 5710, 6350, 210, 722, 217, 732, 6364, 2274, 2281, 2410, 235, 2283, 241, 753, 757, 758, 2294, 2422, 761, 2172}, 1: {771, 772, 2186, 6429, 2338, 6434, 6437, 680, 6441, 2348, 6449, 6451, 6454, 6458, 2391, 2392, 224, 739, 2404, 746, 5738, 6385, 2418, 755}, 2: {1538, 515, 5650, 3604, 3607, 28, 5663, 3634, 1091, 4181, 5726, 2152, 2157, 2165, 2168, 2170, 2171, 3708, 2189, 3731, 2196, 2200, 2205, 6313, 2225, 690, 2227, 4799, 2245, 2251, 716, 2255, 2256, 4818, 723, 6357, 727, 216, 731, 220, 6363, 225, 2276, 3815, 233, 745, 2287, 6383, 6385, 756, 6392, 762, 763, 764, 6403, 6408, 6410, 2316, 3854, 6414, 2320, 2330, 6426, 6428, 2340, 6438, 6439, 6446, 6462, 6463, 2368, 2373, 6469, 2385, 2386, 2413, 2414, 2418, 373, 374, 2424, 2428, 2432, 2436, 2442, 2446}, 3: {5056, 6176, 2242, 3970, 2185, 5356, 6172, 622, 6381, 2161, 6162, 4211, 757, 6134, 6361, 5052, 509}, 4: {5636, 5640, 5650, 5651, 6191, 2147, 2154, 2181, 2184, 2185, 673, 167, 170, 2223, 688, 689, 691, 692, 693, 696, 697, 698, 699, 702, 703, 704, 2241, 706, 707, 708, 712, 713, 714, 716, 6349, 718, 207, 208, 719, 210, 720, 724, 6350, 726, 727, 728, 6354, 6356, 6357, 6358, 6359, 6360, 6361, 6363, 6365, 6366, 6367, 6368, 6370, 6371, 6372, 6373, 6376, 6377, 6381, 6382, 6383, 6384, 6385, 6386, 6387, 6389, 6390, 6391, 6392, 6393, 6394, 6395, 6402, 6403, 6404, 6405, 6406, 6408, 6409, 6410, 6412, 6413, 6414, 2340, 6438, 2439}, 5: {2049, 6145, 3, 4, 6146, 6147, 6149, 8, 6151, 6152, 11, 12, 6153, 14, 6154, 19, 4116, 4117, 22, 6164, 24, 28, 2078, 6174, 33, 34, 39, 2094, 2095, 6190, 2098, 2100, 54, 6199, 63, 2113, 66, 71, 6216, 73, 2122, 2124, 2131, 6229, 4186, 2140, 2141, 2144, 2145, 6248, 4201, 6252, 4207, 4212, 6274, 4228, 6280, 140, 6285, 6289, 6291, 149, 161, 6305, 163, 164, 6308, 166, 168, 6140, 175, 180, 4278, 183, 4279, 2233, 4280, 187, 4283, 6326, 4286, 191, 4287, 193, 4288, 195, 4289, 197, 4290, 4292, 200, 201, 202, 4293, 4295, 4296, 4297, 4298, 4299, 4300, 4301, 4302, 4303, 4304, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4325, 4326, 4328, 4330, 4331, 4333, 4335, 4336, 4338, 4340, 4346, 4349, 4350, 4352, 4353, 4355, 261, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 271, 4366, 4368, 4369, 4370, 276, 2324, 4372, 4373, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4383, 4384, 4570, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 6444, 2356, 4405, 4406, 4409, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4418, 4419, 4420, 4421, 4424, 4425, 4429, 4431, 4434, 4435, 4437, 4439, 4440, 4441, 4444, 4447, 4448, 4452, 4453, 4454, 4455, 4457, 4458, 4459, 4460, 4461, 4462, 4463, 4464, 4466, 4467, 4469, 4470, 4473, 4474, 4475, 4476, 4477, 386, 4482, 4484, 4485, 4486, 4489, 4490, 4491, 4492, 4493, 4496, 4497, 4498, 4501, 2454, 408, 4504, 4505, 4506, 4507, 4508, 415, 416, 4512, 4515, 4516, 4517, 4518, 4519, 4561, 4521, 426, 4523, 4524, 4525, 4562, 4563, 432, 4528, 4529, 435, 4531, 4532, 4534, 439, 4564, 4565, 4538, 4540, 4541, 4542, 4543, 448, 4544, 4545, 451, 4546, 4548, 4549, 455, 4551, 4553, 4554, 459, 4568, 461, 462, 4557, 464, 465, 466, 467, 468, 469, 470, 4558, 472, 4560, 474, 475, 476, 477, 478, 4566, 480, 481, 4569, 483, 4572, 485, 4573, 487, 488, 4574, 4575, 4580, 4581, 4582, 494, 4583, 4576, 4584, 4586, 4588, 4589, 4577, 4590, 4591, 4592, 4593, 4594, 4595, 4596, 4597, 4598, 4600, 4601, 4603, 4604, 4605, 4607, 4609, 4611, 4612, 4615, 4617, 4618, 523, 4619, 4620, 4621, 4622, 4623, 4626, 4627, 4629, 4630, 4631, 4632, 4633, 4634, 539, 4635, 4636, 4638, 543, 4639, 4640, 4641, 4642, 4643, 549, 4644, 4645, 4647, 4648, 4649, 555, 4650, 4651, 4652, 4653, 560, 561, 4654, 4656, 4657, 2614, 4666, 573, 574, 4678, 4679, 588, 590, 598, 4699, 2658, 610, 611, 612, 2661, 615, 616, 2664, 4709, 4714, 2668, 2669, 2670, 2671, 2672, 625, 2673, 2674, 4722, 2677, 2678, 2679, 2680, 633, 4730, 635, 2683, 2684, 2685, 2687, 4736, 2689, 2690, 2691, 4737, 2694, 4744, 2697, 2698, 651, 4748, 2701, 2702, 2703, 2705, 2706, 2708, 2710, 4759, 2712, 2715, 2716, 2717, 2718, 2720, 2721, 2722, 2724, 2726, 2729, 2730, 2731, 2732, 4777, 2734, 2735, 4783, 2739, 2740, 2742, 2746, 2748, 2749, 2750, 2752, 2756, 2757, 2758, 4804, 2760, 4811, 4815, 2769, 2774, 4823, 4824, 2778, 2782, 2783, 4831, 2786, 2787, 4836, 2789, 2790, 2792, 4841, 2795, 2800, 4850, 2803, 2806, 2808, 2809, 4856, 2811, 4860, 2813, 2815, 4864, 4866, 2819, 774, 4871, 778, 2827, 780, 2828, 2829, 4876, 2833, 2834, 4890, 4897, 4901, 4902, 808, 4907, 4908, 4915, 4917, 4921, 826, 4922, 833, 838, 843, 845, 4945, 851, 853, 4953, 4962, 4966, 4967, 879, 4976, 4980, 4983, 888, 900, 913, 5009, 917, 2967, 5020, 936, 939, 5038, 5041, 951, 5049, 5051, 961, 962, 964, 968, 5069, 5071, 5072, 977, 5075, 5076, 5077, 5078, 985, 997, 998, 5093, 5096, 1001, 1005, 5110, 5111, 5125, 5126, 4567, 5138, 3102, 5155, 5156, 5162, 5169, 1084, 5181, 5187, 1094, 1099, 5197, 5212, 5216, 1128, 1141, 5246, 5248, 1159, 1161, 5260, 5264, 1174, 5284, 1191, 5290, 5294, 5296, 5301, 1221, 1232, 5328, 5330, 5331, 5332, 5333, 5334, 1245, 1252, 5351, 5352, 5353, 5360, 5363, 5378, 1287, 5404, 1311, 5407, 5408, 1314, 5412, 5413, 5415, 5416, 1321, 1322, 5418, 1324, 5419, 5423, 5424, 5426, 5430, 1338, 1342, 5438, 5441, 5443, 5445, 5450, 3403, 5452, 5453, 5454, 5455, 5456, 1362, 5459, 5461, 5462, 5464, 5465, 5466, 5468, 5469, 5470, 1378, 5475, 5476, 5477, 5478, 5480, 5481, 1392, 5489, 5490, 5491, 1399, 1402, 5498, 5499, 5500, 5501, 5502, 5504, 5508, 5511, 5513, 5514, 3468, 5516, 5517, 5518, 3474, 5523, 5530, 5532, 1437, 5535, 5536, 5537, 1445, 5543, 5544, 5545, 5547, 5550, 5552, 5553, 5554, 5555, 5557, 1462, 5559, 5560, 5561, 3515, 5563, 5565, 5567, 1473, 5570, 5573, 5575, 5576, 1483, 1485, 5581, 5584, 1490, 5586, 3541, 5592, 5611, 5613, 1518, 3567, 3569, 5624, 1530, 1534, 5630, 5632, 5634, 5638, 5641, 1551, 1552, 5649, 5662, 1579, 1582, 1588, 5684, 5704, 5721, 3677, 5727, 1635, 1636, 1641, 1642, 1646, 1647, 1648, 5743, 1651, 1652, 1653, 1657, 1658, 1659, 1660, 5765, 1672, 1674, 1677, 1682, 1688, 1689, 1690, 5789, 1697, 1698, 1707, 1710, 1720, 1724, 1727, 1728, 1734, 1738, 5835, 1744, 1749, 1751, 3800, 1754, 5852, 1768, 5867, 1775, 1777, 1778, 1779, 1782, 1784, 3836, 1792, 1795, 3845, 5894, 3855, 1814, 1815, 1819, 5917, 3875, 1832, 1833, 5931, 5939, 1844, 5940, 5941, 1847, 3897, 3903, 1856, 1857, 5962, 1869, 1874, 5972, 1880, 3928, 1884, 3932, 1893, 1894, 1895, 5992, 5998, 1921, 3975, 6025, 3978, 1931, 3990, 1950, 6070, 4025, 6083, 4036, 4038, 1991, 6089, 6090, 4045, 1999, 6096, 4053, 2016, 2017, 2022, 2037, 6133, 2040, 2041, 6138, 2043, 2044}, 6: {6144, 6, 6150, 6151, 6164, 4121, 2074, 4122, 2079, 6175, 36, 4132, 48, 4156, 61, 4158, 4165, 73, 2124, 4173, 78, 79, 4178, 88, 4186, 91, 4190, 6246, 104, 105, 4201, 4206, 4207, 112, 115, 4212, 2167, 4225, 138, 151, 161, 6308, 2214, 2217, 4269, 174, 4278, 4280, 193, 4290, 4295, 200, 4296, 4299, 4300, 6348, 4303, 2261, 2266, 219, 4318, 2271, 2272, 4319, 4320, 4328, 4332, 4333, 4335, 4336, 4340, 4352, 4355, 4358, 4364, 270, 4372, 4375, 4376, 287, 4384, 4388, 4389, 4390, 4391, 297, 298, 299, 4398, 303, 304, 4406, 6457, 4410, 4419, 4429, 336, 4439, 4447, 4448, 4453, 4454, 4456, 367, 4469, 4474, 4475, 386, 4482, 4490, 4523, 4524, 4529, 439, 4549, 4557, 466, 4562, 468, 4563, 4565, 4567, 472, 474, 4578, 485, 4583, 4595, 4604, 4607, 4611, 4617, 523, 4619, 526, 4622, 4623, 2585, 4636, 543, 4641, 546, 548, 2597, 4645, 4649, 592, 601, 613, 2663, 2664, 2668, 622, 631, 632, 633, 2680, 2700, 658, 661, 4762, 2717, 2722, 2730, 4782, 2737, 4789, 2742, 2758, 4826, 2786, 2793, 2798, 2806, 2807, 2808, 2823, 4871, 2828, 2835, 790, 794, 795, 834, 4932, 2890, 843, 4942, 4945, 853, 4962, 870, 4980, 900, 902, 5009, 917, 936, 5034, 943, 5041, 5051, 5069, 5075, 5076, 5088, 5089, 3049, 5109, 5111, 5115, 5126, 5129, 5136, 1067, 1079, 1083, 5183, 5185, 5187, 5190, 5194, 5197, 5200, 5201, 5216, 5221, 5238, 5241, 1159, 1161, 5263, 5265, 5278, 5281, 5282, 5304, 5312, 5316, 1237, 1241, 5356, 5369, 5390, 5391, 3348, 3349, 1308, 5407, 1314, 1320, 5420, 5464, 5465, 5476, 5481, 5493, 5496, 5499, 3453, 5511, 5514, 5517, 5518, 5525, 5534, 5538, 5540, 5550, 1465, 5562, 5563, 5566, 1473, 1481, 5580, 5583, 5584, 3541, 1495, 1523, 3577, 1534, 5634, 5641, 1549, 1551, 5649, 1559, 1569, 1574, 1577, 1579, 1588, 5684, 1600, 5704, 1624, 1639, 5736, 1641, 1647, 5747, 1658, 1669, 1671, 1673, 1682, 1683, 1688, 1689, 3736, 5796, 1717, 3765, 1733, 1736, 1739, 5863, 5867, 1777, 5885, 5891, 5898, 3892, 5946, 1860, 3909, 3912, 3915, 3916, 5965, 5969, 3923, 5972, 5974, 1893, 1894, 5992, 3952, 3962, 3963, 6010, 3966, 6028, 6029, 3989, 3991, 6042, 6047, 4002, 6062, 6067, 6092, 6093, 1999, 6096, 6102, 4073, 4083, 4086, 4088, 6137, 6139, 6140, 6143}, 7: {6146, 4, 2053, 6, 2054, 8, 6148, 6155, 12, 14, 15, 19, 22, 24, 2073, 6170, 29, 30, 2078, 33, 34, 6180, 6183, 6186, 2091, 2094, 2095, 6192, 51, 2099, 2101, 6196, 6199, 2107, 2113, 66, 71, 83, 2131, 2138, 6235, 2144, 6241, 6242, 6248, 6250, 2155, 6256, 116, 6267, 6272, 6276, 6277, 6280, 137, 6281, 6282, 145, 6289, 149, 6293, 4249, 156, 6301, 6306, 6307, 164, 6308, 6309, 6312, 172, 173, 174, 176, 177, 180, 182, 4278, 184, 4280, 4281, 187, 6327, 189, 4288, 6336, 195, 196, 197, 4292, 4295, 4296, 6342, 202, 4300, 4308, 4309, 4311, 4312, 4313, 4316, 4317, 4318, 4320, 4325, 236, 4333, 259, 260, 4358, 4363, 4380, 4381, 4383, 4387, 2341, 4389, 4393, 4398, 4406, 4419, 4420, 2374, 4423, 4434, 4435, 4439, 4455, 361, 4460, 365, 366, 367, 368, 4461, 4462, 4466, 4467, 4469, 4470, 4474, 4475, 385, 4485, 4486, 4487, 4490, 4491, 4492, 4504, 4506, 414, 415, 417, 419, 4515, 4518, 2471, 4519, 428, 429, 4532, 437, 439, 441, 4538, 4542, 4544, 4546, 452, 4549, 455, 457, 463, 464, 465, 466, 467, 4559, 4560, 472, 477, 478, 4575, 482, 486, 4582, 493, 494, 4591, 4593, 499, 4597, 4603, 4607, 4611, 519, 4617, 4619, 524, 4622, 528, 4626, 4627, 4628, 4639, 4640, 4643, 549, 550, 4645, 552, 4648, 554, 555, 4651, 4652, 4657, 4658, 4660, 2614, 4662, 4666, 573, 4678, 586, 590, 591, 4687, 593, 595, 4691, 4693, 602, 603, 604, 605, 606, 2655, 607, 609, 2658, 4702, 612, 2660, 4709, 615, 616, 617, 2664, 4710, 4714, 4715, 2670, 4716, 2672, 4717, 2674, 2677, 2678, 2680, 2682, 2683, 2684, 4730, 2687, 2688, 2689, 2690, 643, 4739, 2695, 2696, 649, 2698, 651, 4748, 2701, 2703, 656, 2706, 662, 2710, 4758, 4759, 2716, 4764, 2720, 2721, 2722, 4772, 2725, 2726, 2728, 4777, 2730, 2731, 2734, 2735, 4784, 2737, 2739, 4788, 4791, 2744, 2748, 2750, 2752, 2753, 2754, 2755, 4800, 2757, 4804, 2759, 2760, 4805, 2764, 2765, 4816, 2770, 2771, 2772, 4821, 2775, 2776, 2783, 4833, 2786, 2788, 2789, 2793, 2794, 2795, 4841, 2800, 2801, 2802, 2803, 2804, 4850, 2806, 2808, 4856, 2811, 4859, 2815, 2816, 2819, 4868, 2823, 778, 2826, 2828, 2832, 2833, 2834, 4891, 4893, 4897, 4899, 804, 4901, 4902, 4903, 811, 4912, 826, 4924, 841, 4938, 843, 4941, 4942, 4943, 850, 4954, 866, 4971, 4990, 4995, 4996, 4997, 920, 5016, 5023, 5025, 5030, 5032, 5033, 5037, 5041, 5067, 5072, 5075, 5076, 5078, 3034, 5086, 3049, 1002, 5103, 3056, 3061, 5111, 3064, 5114, 3068, 5118, 5119, 3076, 3080, 3081, 3085, 3090, 3102, 3106, 5162, 3133, 3135, 5186, 5187, 3141, 3143, 3144, 3146, 3150, 5207, 3161, 5210, 3174, 3179, 1137, 3191, 5240, 5241, 3197, 5245, 5260, 3216, 3221, 3225, 3239, 3242, 3243, 3244, 5296, 5299, 3253, 5301, 5304, 3262, 3263, 5325, 3284, 5333, 3289, 3290, 5342, 5343, 5345, 3300, 5353, 3306, 5358, 3322, 3331, 3332, 3333, 1289, 3338, 3345, 3346, 1299, 3351, 5406, 5407, 5409, 5410, 5413, 5417, 3370, 5419, 3372, 3374, 3375, 3376, 3377, 3378, 5422, 5426, 5427, 3382, 1335, 5429, 5430, 5432, 5433, 5435, 5436, 5437, 3391, 5439, 5440, 5441, 5443, 3396, 5444, 5446, 5447, 3403, 3406, 3410, 3411, 3412, 5461, 5462, 5464, 5465, 3418, 3419, 3420, 3423, 3424, 5471, 5473, 3429, 5477, 5481, 3434, 5483, 5484, 5485, 3438, 5487, 3440, 3441, 1394, 5491, 3446, 5502, 5503, 5506, 5507, 5508, 5510, 5514, 5515, 5519, 5525, 5527, 5528, 5529, 5530, 5532, 5534, 5536, 5537, 5539, 5541, 5542, 5545, 5553, 5555, 5560, 5562, 5563, 5567, 5568, 5569, 5573, 5575, 5576, 5580, 5581, 5583, 5585, 5590, 1495, 1506, 5613, 5614, 5634, 1540, 5638, 5648, 5662, 5671, 1582, 5682, 3645, 5704, 5705, 3663, 3664, 5716, 1629, 1630, 1634, 1637, 1641, 5742, 5743, 5744, 5745, 5746, 5747, 5749, 1657, 1658, 1669, 1671, 1680, 1690, 5789, 1697, 1698, 1699, 1709, 1725, 1727, 1733, 1734, 1751, 1752, 1754, 1758, 1760, 5866, 1779, 1782, 1783, 5882, 1793, 1798, 1799, 5894, 1802, 1803, 1805, 1812, 1820, 1826, 5924, 1832, 1833, 3881, 5939, 1850, 1853, 5957, 1866, 5962, 1874, 1876, 1893, 1895, 1905, 6003, 1914, 1919, 6025, 1937, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1962, 6058, 1964, 1974, 6070, 1981, 6081, 6083, 6089, 6094, 2012, 2016, 2017, 2022, 2030, 2037, 2038, 2039, 6137, 2047}, 8: {2050, 2051, 2053, 2054, 2057, 11, 4108, 14, 2062, 16, 2064, 2065, 2066, 2067, 2069, 23, 2071, 25, 28, 34, 35, 36, 2082, 2083, 39, 2085, 2087, 2089, 2090, 6180, 6191, 4144, 51, 6200, 4153, 6203, 2110, 6207, 4162, 2115, 2117, 2118, 2119, 4168, 4169, 74, 76, 4173, 2127, 2134, 6231, 6232, 2140, 2141, 2143, 2149, 103, 2152, 2153, 2154, 6248, 6251, 6252, 6254, 4207, 2160, 4209, 6260, 4220, 2180, 6278, 4234, 4235, 6284, 4237, 4239, 6289, 146, 147, 2194, 2199, 6296, 2206, 163, 168, 2222, 176, 6321, 2233, 6332, 2237, 6335, 192, 195, 2246, 2250, 6348, 2259, 2263, 4312, 6360, 218, 219, 4314, 4315, 6365, 6368, 6371, 4325, 4326, 4327, 6377, 236, 6381, 6383, 2290, 246, 2294, 6390, 2297, 2301, 6402, 6403, 262, 4359, 4363, 6411, 6415, 6418, 2324, 281, 2330, 4379, 285, 292, 6440, 2345, 2347, 2348, 299, 303, 2351, 4399, 4402, 6448, 2356, 312, 2361, 2362, 2363, 4412, 2365, 6461, 2385, 2388, 2393, 358, 2407, 2411, 2412, 4461, 2415, 368, 371, 2419, 2421, 2425, 391, 2439, 396, 398, 399, 2446, 2449, 2452, 4513, 2468, 421, 422, 423, 424, 2471, 427, 2480, 4530, 435, 2486, 2490, 2492, 449, 451, 4554, 4555, 460, 2510, 2519, 2529, 482, 508, 4607, 516, 4618, 4621, 526, 2580, 4638, 544, 2597, 550, 551, 560, 4657, 2613, 4663, 4664, 2617, 2632, 2633, 2635, 594, 2654, 2655, 4703, 620, 2674, 635, 4731, 2686, 4744, 4749, 655, 4760, 2715, 669, 4768, 673, 4773, 4779, 2738, 4786, 692, 4790, 4792, 4795, 705, 4802, 709, 2757, 711, 4806, 2763, 4811, 2765, 718, 2769, 4821, 2775, 728, 731, 732, 4830, 4834, 2788, 748, 4845, 752, 754, 2809, 2827, 2829, 2830, 786, 789, 791, 797, 2850, 4903, 815, 4911, 4915, 820, 826, 2874, 4927, 2884, 4932, 843, 849, 4952, 2905, 2907, 865, 4962, 2922, 876, 877, 2924, 4976, 2931, 4979, 2945, 900, 2949, 903, 2969, 2972, 2973, 927, 5025, 5027, 5031, 944, 5040, 5042, 5046, 5052, 5056, 3010, 5062, 5065, 3020, 986, 987, 3034, 3042, 995, 5091, 5092, 1002, 5107, 5109, 5128, 5133, 5137, 5154, 5165, 5169, 5173, 5176, 5178, 1090, 1093, 1097, 5201, 3170, 1123, 3171, 1143, 5240, 5241, 5245, 5253, 1158, 5255, 5263, 1174, 5270, 3224, 5271, 3232, 1197, 5304, 3268, 3269, 3270, 3271, 5317, 5335, 5352, 5358, 3312, 1266, 3317, 1282, 5380, 1296, 5395, 5412, 3366, 5418, 1325, 1328, 1330, 5428, 5438, 3393, 1350, 1353, 5449, 1357, 5464, 3418, 3425, 5476, 1386, 1387, 1388, 5485, 3438, 1394, 3444, 5494, 5497, 5498, 1408, 3460, 1414, 5512, 1437, 3485, 3491, 5539, 5542, 5550, 3512, 5562, 5568, 5570, 3531, 5583, 1491, 3553, 1509, 3561, 1523, 1532, 3587, 3588, 1541, 3590, 5641, 5648, 5659, 5670, 1582, 5683, 5684, 5689, 5698, 5703, 5705, 3670, 3675, 1632, 1633, 5728, 5732, 5733, 1638, 1642, 3691, 3698, 1652, 1655, 5751, 1657, 5756, 1662, 5758, 3722, 5771, 1678, 1681, 5781, 1686, 3738, 5786, 1693, 1695, 1702, 1705, 3754, 5802, 5806, 1716, 1717, 1721, 1726, 5822, 1736, 1737, 5832, 3796, 3799, 1753, 5850, 5853, 1766, 1770, 1771, 1772, 1773, 5869, 1776, 1780, 5876, 5883, 1788, 1791, 1792, 1797, 5895, 1808, 5907, 1821, 1825, 5923, 5925, 3881, 1836, 1837, 3884, 1839, 1840, 3886, 3895, 3896, 3901, 1854, 3905, 1862, 1863, 1866, 3914, 1868, 1870, 3922, 1875, 1880, 1884, 1885, 1886, 3937, 1892, 1893, 5999, 1904, 1908, 1909, 1911, 3962, 3967, 6016, 3970, 1926, 1927, 6023, 1930, 3982, 1936, 1937, 3984, 6036, 3999, 1956, 4005, 4010, 1965, 1966, 4014, 6066, 1971, 1972, 1973, 4022, 6068, 6075, 1980, 6079, 4032, 1986, 4035, 6082, 4037, 6084, 4039, 1993, 1994, 1995, 4045, 4046, 2000, 2002, 6102, 2010, 4062, 4063, 6111, 4069, 4072, 2028, 6124, 2036, 6136, 2041, 4091, 2046}, 9: {1537, 2, 3586, 1540, 3588, 5641, 3596, 1529, 1551, 4626, 4627, 4628, 3616, 37, 38, 39, 1579, 45, 46, 1069, 48, 49, 50, 1071, 1072, 53, 1078, 1079, 1591, 1592, 58, 1084, 3644, 1086, 1087, 1088, 65, 1091, 1092, 3651, 72, 3658, 75, 1101, 79, 80, 3686, 3695, 2675, 1141, 1142, 1654, 1144, 3702, 1147, 124, 1149, 1150, 2171, 1152, 3711, 130, 131, 1156, 133, 1158, 1159, 1160, 1161, 1162, 1673, 3719, 1165, 1166, 1167, 3726, 1174, 2722, 3747, 5630, 2731, 2225, 3762, 4280, 1220, 1222, 4295, 1228, 1229, 1230, 1231, 1234, 3794, 1237, 1749, 1239, 3803, 1762, 3811, 1252, 2796, 3820, 4339, 3828, 3844, 4367, 1296, 2320, 3859, 1300, 4373, 1303, 5405, 5406, 1312, 4384, 1317, 1319, 1320, 1321, 1322, 1323, 1328, 1330, 823, 831, 833, 835, 838, 843, 845, 850, 851, 3630, 857, 859, 860, 863, 864, 865, 866, 868, 1383, 874, 1386, 878, 879, 880, 881, 1390, 883, 1395, 1401, 1403, 893, 894, 382, 896, 1406, 1407, 1413, 902, 395, 908, 909, 3468, 911, 912, 2451, 916, 918, 4502, 922, 411, 412, 925, 3485, 927, 3487, 417, 932, 934, 944, 946, 947, 1460, 5554, 1462, 951, 952, 1463, 1465, 1466, 1467, 957, 958, 959, 960, 961, 962, 1471, 964, 1473, 3520, 1479, 1486, 1487, 1488, 977, 978, 979, 980, 1489, 986, 4573, 991, 992, 994, 3557, 1000, 1517, 495, 1008, 1521, 1522, 3569, 1012, 1017, 1530, 1019, 5629, 1534, 1535}, 10: {2, 28, 37, 39, 42, 43, 46, 47, 48, 50, 53, 59, 60, 65, 72, 75, 76, 80, 81, 124, 125, 126, 127, 130, 132, 133, 4234, 4251, 6329, 4301, 4334, 245, 4367, 4391, 6449, 4459, 4464, 4484, 2451, 404, 4502, 412, 414, 4526, 4550, 4573, 491, 495, 519, 4628, 4630, 680, 4797, 2765, 2795, 4868, 823, 828, 829, 832, 833, 834, 838, 840, 843, 845, 846, 847, 850, 851, 853, 854, 857, 858, 859, 860, 862, 864, 867, 869, 872, 873, 874, 879, 880, 883, 887, 888, 889, 890, 891, 893, 895, 896, 897, 901, 902, 903, 904, 907, 908, 909, 911, 915, 916, 917, 918, 919, 921, 922, 925, 926, 927, 931, 933, 934, 936, 5037, 944, 945, 949, 950, 958, 959, 962, 963, 964, 968, 972, 976, 978, 979, 984, 986, 988, 993, 994, 5093, 1000, 1001, 1002, 5097, 1008, 1009, 1012, 1013, 1016, 1017, 1018, 1019, 5160, 5161, 1069, 1071, 1073, 1074, 1077, 1078, 5174, 1080, 1081, 1082, 1083, 5175, 1085, 1088, 1089, 1092, 1093, 1094, 1098, 1099, 5202, 5205, 1141, 1144, 1146, 1147, 1148, 1149, 1150, 1151, 1157, 1158, 1159, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1170, 1171, 1174, 1175, 5299, 1220, 1221, 1223, 1224, 1226, 1227, 1228, 1229, 1230, 1233, 1234, 1236, 1237, 1240, 1242, 1244, 1248, 1249, 1252, 1297, 1299, 1301, 1302, 1303, 1306, 1308, 1312, 1313, 1316, 1317, 1319, 1320, 1323, 1325, 1327, 1328, 1329, 1330, 1332, 5452, 1378, 1380, 1388, 1389, 1390, 1393, 1395, 1397, 1398, 1401, 1403, 1404, 1407, 1408, 1409, 1412, 5508, 3470, 3473, 3476, 3478, 3485, 3489, 3506, 1460, 1461, 1462, 1463, 1465, 1466, 3516, 1468, 1469, 1470, 5567, 1473, 1475, 1476, 1477, 3526, 1478, 1479, 1481, 1483, 1485, 1487, 1488, 1489, 1490, 3537, 3542, 3547, 3551, 3553, 3554, 3557, 3559, 1517, 1519, 1520, 3569, 1521, 1522, 1524, 1526, 3576, 1529, 1530, 1531, 1532, 1533, 3581, 1535, 1536, 1537, 1538, 1539, 1540, 5637, 1543, 1545, 1546, 3595, 1550, 1551, 3601, 3606, 3607, 3610, 3611, 5672, 1579, 1580, 1581, 3630, 1586, 3644, 3651, 3661, 3667, 3673, 1631, 3687, 3700, 1654, 3702, 5762, 3720, 3731, 3745, 3748, 1710, 3758, 1713, 3766, 3770, 3771, 3773, 3794, 3807, 3811, 3817, 3832, 3838, 3842, 3865, 3876, 1853, 4034, 6083}, 11: {2, 69, 76, 80, 127, 2210, 171, 2234, 2244, 4301, 211, 6357, 232, 4344, 2300, 257, 2308, 4377, 6438, 5629, 4400, 4404, 309, 5630, 2397, 373, 374, 375, 376, 377, 4473, 380, 381, 382, 383, 384, 4478, 386, 387, 388, 389, 391, 393, 395, 396, 397, 400, 402, 404, 2

In [41]:
import pickle

with open('groundtruth_min2.pkl', 'wb') as f:
    pickle.dump(ground_truth_map, f)
print("Đã lưu file 'groundtruth_min2.pkl'")

Đã lưu file 'groundtruth_min2.pkl'

In [42]:
with open('groundtruth_min2.pkl', 'rb') as f:
    loaded_groundtruth = pickle.load(f)


## Đánh giá

In [43]:
df_eval = pd.read_excel('kq.xlsx')

In [44]:
df_eval['model'] = df_eval['model_short'].astype(str) + " " + df_eval['model_type'].astype(str)
df_eval['model'].value_counts()

model
tfidf basic             400
tfidf upgrade           400
ensemble basic          400
mpnet upgrade           400
mpnet basic             400
bge upgrade             400
bge basic               400
labse upgrade           400
labse basic             400
doc2vec_dbow upgrade    400
doc2vec_dbow basic      400
doc2vec upgrade         400
doc2vec basic           400
w2v_sg upgrade          400
w2v_sg basic            400
w2v upgrade             400
w2v basic               400
ensemble upgrade        400
Name: count, dtype: int64

In [33]:
dev_manual = pd.read_excel('kq.xlsx')

In [34]:
dev_manual['model'] = dev_manual['model_short'].astype(str) + " " + dev_manual['model_type'].astype(str)
dev_manual['model'].value_counts()

model
tfidf basic             400
tfidf upgrade           400
ensemble basic          400
mpnet upgrade           400
mpnet basic             400
bge upgrade             400
bge basic               400
labse upgrade           400
labse basic             400
doc2vec_dbow upgrade    400
doc2vec_dbow basic      400
doc2vec upgrade         400
doc2vec basic           400
w2v_sg upgrade          400
w2v_sg basic            400
w2v upgrade             400
w2v basic               400
ensemble upgrade        400
Name: count, dtype: int64

In [35]:
cols = ['model','query_id', 'rank', 'score', 'id', 'label']
dev_manual_short = dev_manual[cols]
dev_manual_short.head()

         model  query_id  rank     score    id  label
0  tfidf basic         0     1  0.434380  2453    0.0
1  tfidf basic         0     2  0.424796  2311    0.0
2  tfidf basic         0     3  0.399933  2281    0.0
3  tfidf basic         0     4  0.331504  4571    1.0
4  tfidf basic         0     5  0.306119   746    0.0

In [36]:
dev_manual_short.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   model     7200 non-null   object
 1   query_id  7200 non-null   int64
 2   rank      7200 non-null   int64
 3   score     7200 non-null   float64
 4   id        7200 non-null   int64
 5   label     3601 non-null   float64
dtypes: float64(2), int64(3), object(1)
memory usage: 337.6+ KB

In [37]:
dev_manual_short = dev_manual_short[dev_manual_short['rank'] <= 10] 
dev_manual_short.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3600 entries, 0 to 7189
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   model     3600 non-null   object
 1   query_id  3600 non-null   int64
 2   rank      3600 non-null   int64
 3   score     3600 non-null   float64
 4   id        3600 non-null   int64
 5   label     3600 non-null   float64
dtypes: float64(2), int64(3), object(1)
memory usage: 196.9+ KB

In [38]:
dev_manual_short['label'] = dev_manual_short['label'].replace({1: 0, 0: 1})
dev_manual_short.head()

         model  query_id  rank     score    id  label
0  tfidf basic         0     1  0.434380  2453    1.0
1  tfidf basic         0     2  0.424796  2311    1.0
2  tfidf basic         0     3  0.399933  2281    1.0
3  tfidf basic         0     4  0.331504  4571    0.0
4  tfidf basic         0     5  0.306119   746    1.0

In [39]:
dev_manual_short.to_excel('dev_manual_short_min2.xlsx', index=False)

Đánh giá thủ công

In [43]:
import pandas as pd
import numpy as np

def calculate_metrics_manual(group):
    # Lấy thông tin index
    if isinstance(group.name, tuple):
        model_name, q_id = group.name
    else:
        q_id = group.name
    
    # 1. Sắp xếp theo rank (1 -> 10)
    group = group.sort_values('rank')
    
    # Lấy nhãn (chỉ lấy tối đa 10 dòng đầu vì đánh giá thủ công Top 10)
    relevants = group['label'].values[:10]
    
    metrics = {}

    # ====================================================
    # A. MRR (Mean Reciprocal Rank)
    # ====================================================
    try:
        first_rel_idx = np.argmax(relevants == 1)
        if relevants[first_rel_idx] == 1:
            metrics['MRR'] = 1 / (first_rel_idx + 1)
        else:
            metrics['MRR'] = 0
    except:
        metrics['MRR'] = 0

    # ====================================================
    # B. METRICS TẠI CÁC NGƯỠNG K (5, 10)
    # ====================================================
    cutoffs = [5, 10]
    
    # Bảng discount cho NDCG
    global_discounts = np.log2(np.arange(len(relevants)) + 2)
    
    for k in cutoffs:
        actual_k = min(k, len(relevants))
        
        # Cắt mảng kết quả
        r_k = relevants[:actual_k]
        d_k = global_discounts[:actual_k]
        
        # --- 1. Hit Ratio@K (MỚI BỔ SUNG) ---
        # Ý nghĩa: Có ít nhất 1 kết quả đúng trong top K không?
        metrics[f'Hit@{k}'] = 1 if np.sum(r_k) > 0 else 0
        
        # --- 2. Precision@K ---
        metrics[f'P@{k}'] = np.sum(r_k) / k 
        
        # --- 3. NDCG@K ---
        dcg = np.sum(r_k / d_k)
        
        # IDCG (Lý tưởng: đưa hết các kết quả đúng tìm được lên đầu)
        ideal_r_k = sorted(r_k, reverse=True)
        idcg = np.sum(ideal_r_k / d_k)
        
        metrics[f'NDCG@{k}'] = dcg / idcg if idcg > 0 else 0

    return pd.Series(metrics)

# --- EXAMPLE USAGE ---
# manual_eval_df = pd.read_excel('manual_labels.xlsx') 
# report = manual_eval_df.groupby(['model', 'query_id']).apply(calculate_metrics_manual).reset_index()
# print(report.groupby('model').mean())
# --- HƯỚNG DẪN SỬ DỤNG ---
# Giả sử dataframe 'manual_eval_df' có các cột: [model, query_id, rank, label]
# rank: 1 đến 10
# label: 0 hoặc 1 (do người chấm)

final_report = dev_manual_short.groupby(['model', 'query_id']).apply(calculate_metrics_manual).reset_index()
summary = final_report.groupby('model').mean()
print(summary)

                      query_id       MRR  Hit@5   P@5    NDCG@5  Hit@10  \
model
bge basic                  9.5  0.750000   0.85  0.58  0.759038    0.95
bge upgrade                9.5  0.775000   0.90  0.69  0.804887    0.90
doc2vec basic              9.5  0.436310   0.55  0.28  0.449320    0.60
doc2vec upgrade            9.5  0.116667   0.15  0.07  0.128532    0.15
doc2vec_dbow basic         9.5  0.557917   0.70  0.44  0.583575    0.75
doc2vec_dbow upgrade       9.5  0.662083   0.80  0.50  0.676310    0.90
ensemble basic             9.5  0.860000   0.95  0.68  0.885999    0.95
ensemble upgrade           9.5  0.861310   0.95  0.68  0.870608    1.00
labse basic                9.5  0.645833   0.75  0.57  0.666987    0.85
labse upgrade              9.5  0.661310   0.85  0.62  0.706915    0.90
mpnet basic                9.5  0.541667   0.65  0.51  0.558391    0.75
mpnet upgrade              9.5  0.688333   0.75  0.63  0.703122    0.85
tfidf basic                9.5  0.857917   0.95  0.68  0.843519    1.00
tfidf upgrade              9.5  0.727083   0.80  0.62  0.730729    0.90
w2v basic                  9.5  0.005000   0.00  0.00  0.000000    0.05
w2v upgrade                9.5  0.075000   0.10  0.07  0.083131    0.10
w2v_sg basic               9.5  0.426389   0.55  0.29  0.440735    0.60
w2v_sg upgrade             9.5  0.007143   0.00  0.00  0.000000    0.05

                       P@10   NDCG@10
model
bge basic             0.565  0.787845
bge upgrade           0.610  0.799979
doc2vec basic         0.265  0.464007
doc2vec upgrade       0.055  0.130374
doc2vec_dbow basic    0.390  0.593094
doc2vec_dbow upgrade  0.480  0.707792
ensemble basic        0.600  0.868452
ensemble upgrade      0.630  0.887600
labse basic           0.560  0.703042
labse upgrade         0.570  0.731048
mpnet basic           0.470  0.592578
mpnet upgrade         0.565  0.734105
tfidf basic           0.625  0.849702
tfidf upgrade         0.570  0.769055
w2v basic             0.005  0.014453
w2v upgrade           0.075  0.085049
w2v_sg basic          0.285  0.459953
w2v_sg upgrade        0.005  0.016667

In [44]:
summary.to_excel('manual_validation.xlsx')

In [12]:
import pickle
GROUNDTRUTH_FILE = 'groundtruth_min2.pkl'  # File đáp án chuẩn của bạn
K_LIST = [5, 10, 20] 
with open(GROUNDTRUTH_FILE, 'rb') as f:
    ground_truth = pickle.load(f)

In [47]:
print(ground_truth)

{0: {769, 770, 2307, 2308, 2311, 6408, 2443, 2197, 2453, 23, 2204, 2337, 2210, 2343, 685, 690, 6450, 6452, 5687, 6462, 2240, 2241, 716, 5710, 6350, 210, 722, 217, 732, 6364, 2274, 2281, 2410, 235, 2283, 241, 753, 757, 758, 2294, 2422, 761, 2172}, 1: {771, 772, 2186, 6429, 2338, 6434, 6437, 680, 6441, 2348, 6449, 6451, 6454, 6458, 2391, 2392, 224, 739, 2404, 746, 5738, 6385, 2418, 755}, 2: {1538, 515, 5650, 3604, 3607, 28, 5663, 3634, 1091, 4181, 5726, 2152, 2157, 2165, 2168, 2170, 2171, 3708, 2189, 3731, 2196, 2200, 2205, 6313, 2225, 690, 2227, 4799, 2245, 2251, 716, 2255, 2256, 4818, 723, 6357, 727, 216, 731, 220, 6363, 225, 2276, 3815, 233, 745, 2287, 6383, 6385, 756, 6392, 762, 763, 764, 6403, 6408, 6410, 2316, 3854, 6414, 2320, 2330, 6426, 6428, 2340, 6438, 6439, 6446, 6462, 6463, 2368, 2373, 6469, 2385, 2386, 2413, 2414, 2418, 373, 374, 2424, 2428, 2432, 2436, 2442, 2446}, 3: {5056, 6176, 2242, 3970, 2185, 5052, 5356, 6381, 622, 2161, 6162, 4211, 757, 6134, 6361, 6172, 509}, 4: {5636, 5640, 5650, 5651, 6191, 2147, 2154, 2181, 2184, 2185, 673, 167, 170, 2223, 688, 689, 691, 692, 693, 696, 697, 698, 699, 702, 703, 704, 2241, 706, 707, 708, 712, 713, 714, 716, 6349, 718, 207, 208, 719, 210, 720, 724, 6350, 726, 727, 728, 6354, 6356, 6357, 6358, 6359, 6360, 6361, 6363, 6365, 6366, 6367, 6368, 6370, 6371, 6372, 6373, 6376, 6377, 6381, 6382, 6383, 6384, 6385, 6386, 6387, 6389, 6390, 6391, 6392, 6393, 6394, 6395, 6402, 6403, 6404, 6405, 6406, 6408, 6409, 6410, 6412, 6413, 6414, 2340, 6438, 2439}, 5: {2049, 6146, 3, 4, 6145, 6147, 6149, 8, 6151, 6152, 11, 12, 6153, 14, 6154, 19, 4116, 4117, 22, 6164, 24, 28, 2078, 6174, 33, 34, 39, 2044, 2094, 2095, 6190, 2098, 2100, 54, 6199, 63, 2113, 66, 71, 6216, 73, 2122, 2124, 2131, 6229, 4186, 2140, 2141, 2144, 2145, 6248, 4201, 6252, 4207, 4212, 6274, 4228, 6280, 140, 6285, 6289, 6291, 149, 161, 6305, 163, 164, 6308, 166, 168, 175, 180, 4278, 183, 4279, 2233, 4280, 187, 4283, 6326, 4286, 191, 4287, 193, 4288, 195, 4289, 197, 4290, 4292, 200, 201, 202, 4293, 4295, 4296, 4297, 4298, 4299, 4300, 4301, 4302, 4303, 4304, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4325, 4326, 4328, 4330, 4331, 4333, 4335, 4336, 4338, 4340, 4346, 4349, 4350, 4352, 4353, 4355, 261, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 271, 4366, 4368, 4369, 4370, 276, 2324, 4372, 4373, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4383, 4384, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 6444, 2356, 4405, 4406, 4409, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4418, 4419, 4420, 4421, 4424, 4425, 4572, 4429, 4431, 4434, 4435, 4437, 4439, 4440, 4441, 4444, 4447, 4448, 4452, 4453, 4454, 4455, 4573, 4457, 4458, 4459, 4460, 4461, 4462, 4463, 4464, 4466, 4467, 4469, 4470, 4473, 4474, 4475, 4476, 4477, 386, 4482, 4484, 4485, 4486, 4489, 4490, 4491, 4492, 4493, 4496, 4497, 4498, 4501, 2454, 408, 4504, 4505, 4506, 4507, 4508, 415, 416, 4512, 4515, 4516, 4517, 4518, 4519, 4521, 426, 4523, 4524, 4525, 432, 4528, 4529, 435, 4531, 4532, 4534, 439, 4538, 4540, 4541, 4542, 4543, 448, 4544, 4545, 451, 4546, 4548, 4549, 455, 4551, 4553, 4554, 459, 4569, 461, 4558, 462, 4560, 4557, 464, 4561, 4562, 4563, 4564, 4565, 465, 466, 4568, 467, 4570, 468, 469, 470, 472, 474, 475, 476, 477, 478, 480, 481, 483, 485, 487, 488, 4574, 4575, 4581, 4582, 494, 4576, 4586, 4588, 4589, 4577, 4590, 4591, 4592, 4593, 4594, 4595, 4596, 4597, 4598, 4600, 4601, 4603, 4604, 4605, 4580, 4607, 4609, 4611, 4612, 4615, 4617, 4618, 523, 4619, 4620, 4621, 4622, 4623, 4626, 4583, 4627, 4629, 4630, 4631, 4584, 4632, 4633, 4634, 539, 4635, 4636, 4638, 543, 4639, 4640, 4641, 4642, 4643, 549, 4644, 4645, 4647, 4648, 4649, 555, 4650, 4651, 4652, 4653, 560, 561, 4654, 4656, 4657, 2614, 4666, 573, 574, 4678, 4679, 588, 590, 598, 4699, 2658, 610, 611, 612, 2661, 615, 616, 2664, 4709, 4714, 2668, 2669, 2670, 2671, 2672, 625, 2673, 2674, 4722, 2677, 2678, 2679, 2680, 633, 4730, 635, 2683, 2684, 2685, 2687, 4736, 2689, 2690, 2691, 4737, 2694, 4744, 2697, 2698, 651, 4748, 2701, 2702, 2703, 2705, 2706, 2708, 2710, 4759, 2712, 2715, 2716, 2717, 2718, 2720, 2721, 2722, 2724, 2726, 2729, 2730, 2731, 2732, 4777, 2734, 2735, 4783, 2739, 2740, 2742, 2746, 2748, 2749, 2750, 2752, 2756, 2757, 2758, 4804, 2760, 4811, 4815, 2769, 2774, 4823, 4824, 2778, 2782, 2783, 4831, 2786, 2787, 4836, 2789, 2790, 2792, 4841, 2795, 2800, 4850, 2803, 2806, 2808, 2809, 4856, 2811, 4860, 2813, 2815, 4864, 4866, 2819, 774, 4871, 778, 2827, 780, 2828, 2829, 4876, 2833, 2834, 4890, 4897, 4901, 4902, 808, 4907, 4908, 4915, 4917, 4921, 826, 4922, 833, 838, 843, 845, 4945, 851, 853, 4953, 4962, 4966, 4967, 879, 4976, 4980, 4983, 888, 900, 4566, 913, 5009, 917, 2967, 5020, 936, 939, 5038, 5041, 951, 5049, 5051, 961, 962, 964, 968, 5069, 5071, 5072, 977, 5075, 5076, 5077, 5078, 985, 997, 998, 5093, 5096, 1001, 1005, 5110, 5111, 5125, 5126, 4567, 5138, 3102, 5155, 5156, 5162, 5169, 1084, 5181, 5187, 1094, 1099, 5197, 5212, 5216, 1128, 1141, 5246, 5248, 1159, 1161, 5260, 5264, 1174, 5284, 1191, 5290, 5294, 5296, 5301, 1221, 1232, 5328, 5330, 5331, 5332, 5333, 5334, 1245, 1252, 5351, 5352, 5353, 5360, 5363, 5378, 1287, 5404, 1311, 5407, 5408, 1314, 5412, 5413, 5415, 5416, 1321, 1322, 5418, 1324, 5419, 5423, 5424, 5426, 5430, 1338, 1342, 5438, 5441, 5443, 5445, 5450, 3403, 5452, 5453, 5454, 5455, 5456, 1362, 5459, 5461, 5462, 5464, 5465, 5466, 5468, 5469, 5470, 1378, 5475, 5476, 5477, 5478, 5480, 5481, 1392, 5489, 5490, 5491, 1399, 1402, 5498, 5499, 5500, 5501, 5502, 5504, 5508, 5511, 5513, 5514, 3468, 5516, 5517, 5518, 3474, 5523, 5530, 5532, 1437, 5535, 5536, 5537, 1445, 5543, 5544, 5545, 5547, 5550, 5552, 5553, 5554, 5555, 5557, 1462, 5559, 5560, 5561, 3515, 5563, 5565, 5567, 1473, 5570, 5573, 5575, 5576, 1483, 1485, 5581, 5584, 1490, 5586, 3541, 5592, 5611, 5613, 1518, 3567, 3569, 5624, 1530, 1534, 5630, 5632, 5634, 5638, 5641, 1551, 1552, 5649, 5662, 1579, 1582, 1588, 5684, 5704, 5721, 3677, 5727, 1635, 1636, 1641, 1642, 1646, 1647, 1648, 5743, 1651, 1652, 1653, 1657, 1658, 1659, 1660, 5765, 1672, 1674, 1677, 1682, 1688, 1689, 1690, 5789, 1697, 1698, 1707, 1710, 1720, 1724, 1727, 1728, 1734, 1738, 5835, 1744, 1749, 1751, 3800, 1754, 5852, 1768, 5867, 1775, 1777, 1778, 1779, 1782, 1784, 3836, 1792, 1795, 3845, 5894, 3855, 1814, 1815, 1819, 5917, 3875, 1832, 1833, 5931, 5939, 1844, 5940, 5941, 1847, 3897, 3903, 1856, 1857, 5962, 1869, 1874, 5972, 1880, 3928, 1884, 3932, 1893, 1894, 1895, 5992, 5998, 1921, 3975, 6025, 3978, 1931, 3990, 1950, 6070, 4025, 6083, 4036, 4038, 1991, 6089, 6090, 4045, 1999, 6096, 4053, 2016, 2017, 2022, 2037, 6133, 2040, 2041, 6138, 2043, 6140}, 6: {6144, 6, 6151, 6150, 6164, 4121, 4122, 2074, 6175, 2079, 36, 4132, 48, 4156, 61, 4158, 4165, 73, 2124, 4173, 78, 79, 4178, 88, 4186, 91, 4190, 6246, 104, 105, 4201, 4206, 4207, 112, 115, 4212, 2167, 4225, 138, 151, 161, 6308, 2214, 2217, 4269, 174, 4278, 4280, 193, 4290, 4295, 200, 4296, 4299, 4300, 6348, 4303, 2261, 2266, 219, 4318, 2271, 2272, 4319, 4320, 4328, 4332, 4333, 4335, 4336, 4340, 4352, 4355, 4358, 4364, 270, 4372, 4375, 4376, 287, 4384, 4388, 4389, 4390, 4391, 297, 298, 299, 4398, 303, 304, 4406, 6457, 4410, 4419, 4429, 336, 4439, 4447, 4448, 4453, 4454, 4456, 367, 4469, 4474, 4475, 386, 4482, 4490, 4523, 4524, 4529, 439, 4549, 4557, 466, 4562, 468, 4563, 4565, 4567, 472, 474, 4578, 485, 4583, 4595, 4604, 4607, 4611, 4617, 523, 4619, 526, 4622, 4623, 2585, 4636, 543, 4641, 546, 548, 2597, 4645, 4649, 592, 601, 613, 2663, 2664, 2668, 622, 631, 632, 633, 2680, 2700, 658, 661, 4762, 2717, 2722, 2730, 4782, 2737, 4789, 2742, 2758, 4826, 2786, 2793, 2798, 2806, 2807, 2808, 2823, 4871, 2828, 2835, 790, 794, 795, 834, 4932, 2890, 843, 4942, 4945, 853, 4962, 870, 4980, 900, 902, 5009, 917, 936, 5034, 943, 5041, 5051, 5069, 5075, 5076, 5088, 5089, 3049, 5109, 5111, 5115, 5126, 5129, 5136, 1067, 1079, 1083, 5183, 5185, 5187, 5190, 5194, 5197, 5200, 5201, 5216, 5221, 5238, 5241, 1159, 1161, 5263, 5265, 5278, 5281, 5282, 5304, 5312, 5316, 1237, 1241, 5356, 5369, 5390, 5391, 3348, 3349, 1308, 5407, 1314, 1320, 5420, 5464, 5465, 5476, 5481, 5493, 5496, 5499, 3453, 5511, 5514, 5517, 5518, 5525, 5534, 5538, 5540, 5550, 1465, 5562, 5563, 5566, 1473, 1481, 5580, 5583, 5584, 3541, 1495, 1523, 3577, 1534, 5634, 5641, 1549, 1551, 5649, 1559, 1569, 1574, 1577, 1579, 1588, 5684, 1600, 5704, 1624, 1639, 5736, 1641, 1647, 5747, 1658, 1669, 1671, 1673, 1682, 1683, 1688, 1689, 3736, 5796, 1717, 3765, 1733, 1736, 1739, 5863, 5867, 1777, 5885, 5891, 5898, 3892, 5946, 1860, 3909, 3912, 3915, 3916, 5965, 5969, 3923, 5972, 5974, 1893, 1894, 5992, 3952, 3962, 3963, 6010, 3966, 6028, 6029, 3989, 3991, 6042, 6047, 4002, 6062, 6067, 6092, 6093, 1999, 6096, 6102, 4073, 4083, 4086, 4088, 6137, 6139, 6140, 6143}, 7: {6146, 4, 2053, 6, 2054, 8, 6148, 6155, 12, 14, 15, 19, 22, 24, 2073, 6170, 29, 2078, 30, 33, 34, 6180, 6183, 6186, 2091, 2094, 2095, 6192, 51, 2099, 2101, 6196, 6199, 2107, 2113, 66, 71, 83, 2131, 2138, 6235, 2144, 6241, 6242, 6248, 6250, 2155, 6256, 116, 6267, 6272, 6276, 6277, 6280, 137, 6281, 6282, 145, 6289, 149, 6293, 4249, 156, 6301, 6306, 6307, 164, 6308, 6309, 6312, 172, 173, 174, 176, 177, 180, 182, 4278, 184, 4280, 4281, 187, 6327, 189, 4288, 6336, 195, 196, 197, 4292, 4295, 4296, 6342, 202, 4300, 4308, 4309, 4311, 4312, 4313, 4316, 4317, 4318, 4320, 4325, 236, 4333, 259, 260, 4358, 4363, 4380, 4381, 4383, 4387, 2341, 4389, 4393, 4398, 4406, 4419, 4420, 2374, 4423, 4434, 4435, 4439, 4455, 361, 4460, 365, 366, 367, 368, 4461, 4462, 4466, 4467, 4469, 4470, 4474, 4475, 385, 4485, 4486, 4487, 4490, 4491, 4492, 4504, 4506, 414, 415, 417, 419, 4515, 4518, 2471, 4519, 428, 429, 4532, 437, 439, 441, 4538, 4542, 4544, 4546, 452, 4549, 455, 457, 463, 464, 465, 466, 467, 4559, 4560, 472, 477, 478, 4575, 482, 486, 4582, 493, 494, 4591, 4593, 499, 4597, 4603, 4607, 4611, 519, 4617, 4619, 524, 4622, 528, 4626, 4627, 4628, 4639, 4640, 4643, 549, 550, 4645, 552, 4648, 554, 555, 4651, 4652, 4657, 4658, 4660, 2614, 4662, 4666, 573, 4678, 586, 590, 591, 4687, 593, 595, 4691, 4693, 602, 603, 604, 605, 606, 2655, 607, 609, 2658, 4702, 612, 2660, 4709, 615, 616, 617, 4714, 4710, 4715, 4716, 2670, 4717, 2672, 2664, 2674, 2677, 2678, 2680, 2682, 2683, 2684, 4730, 2687, 2688, 2689, 2690, 643, 4739, 2695, 2696, 649, 2698, 651, 4748, 2701, 2703, 656, 2706, 662, 2710, 4758, 4759, 2716, 4764, 2720, 2721, 2722, 4772, 2725, 2726, 2728, 4777, 2730, 2731, 2734, 2735, 4784, 2737, 2739, 4788, 4791, 2744, 2748, 2750, 2752, 2753, 2754, 2755, 4800, 2757, 4804, 2759, 2760, 4805, 2764, 2765, 4816, 2770, 2771, 2772, 4821, 2775, 2776, 2783, 4833, 2786, 2788, 2789, 2793, 2794, 2795, 4841, 2800, 2801, 2802, 2803, 2804, 4850, 2806, 2808, 4856, 2811, 4859, 2815, 2816, 2819, 4868, 2823, 778, 2826, 2828, 2832, 2833, 2834, 4891, 4893, 4897, 4899, 804, 4901, 4902, 4903, 811, 4912, 826, 4924, 841, 4938, 843, 4941, 4942, 4943, 850, 4954, 866, 4971, 4990, 4995, 4996, 4997, 920, 5016, 5023, 5025, 5030, 5032, 5033, 5037, 5041, 5067, 5072, 5075, 5076, 5078, 3034, 5086, 3049, 1002, 5103, 3056, 3061, 5111, 3064, 5114, 3068, 5118, 5119, 3076, 3080, 3081, 3085, 3090, 3102, 3106, 5162, 3133, 3135, 5186, 5187, 3141, 3143, 3144, 3146, 3150, 5207, 3161, 5210, 3174, 3179, 1137, 3191, 5240, 5241, 3197, 5245, 5260, 3216, 3221, 3225, 3239, 3242, 3243, 3244, 5296, 5299, 3253, 5301, 5304, 3262, 3263, 5325, 3284, 5333, 3289, 3290, 5342, 5343, 5345, 3300, 5353, 3306, 5358, 3322, 3331, 3332, 3333, 1289, 3338, 3345, 3346, 1299, 3351, 5406, 5407, 5409, 5410, 5413, 5417, 3370, 5419, 3372, 3374, 3375, 3376, 3377, 3378, 5422, 5426, 5427, 3382, 1335, 5429, 5430, 5432, 5433, 5435, 5436, 5437, 3391, 5439, 5440, 5441, 5443, 3396, 5444, 5446, 5447, 3403, 3406, 3410, 3411, 3412, 5461, 5462, 5464, 5465, 3418, 3419, 3420, 3423, 3424, 5471, 5473, 3429, 5477, 5481, 3434, 5483, 5484, 5485, 3438, 5487, 3440, 3441, 1394, 5491, 3446, 5502, 5503, 5506, 5507, 5508, 5510, 5514, 5515, 5519, 5525, 5527, 5528, 5529, 5530, 5532, 5534, 5536, 5537, 5539, 5541, 5542, 5545, 5553, 5555, 5560, 5562, 5563, 5567, 5568, 5569, 5573, 5575, 5576, 5580, 5581, 5583, 5585, 5590, 1495, 1506, 5613, 5614, 5634, 1540, 5638, 5648, 5662, 5671, 1582, 5682, 3645, 5704, 5705, 3663, 3664, 5716, 1629, 1630, 1634, 1637, 1641, 5742, 5743, 5744, 5745, 5746, 5747, 5749, 1657, 1658, 1669, 1671, 1680, 1690, 5789, 1697, 1698, 1699, 1709, 1725, 1727, 1733, 1734, 1751, 1752, 1754, 1758, 1760, 5866, 1779, 1782, 1783, 5882, 1793, 1798, 1799, 5894, 1802, 1803, 1805, 1812, 1820, 1826, 5924, 1832, 1833, 3881, 5939, 1850, 1853, 5957, 1866, 5962, 1874, 1876, 1893, 1895, 1905, 6003, 1914, 1919, 6025, 1937, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1962, 6058, 1964, 1974, 6070, 1981, 6081, 6083, 6089, 6094, 2012, 2016, 2017, 2022, 2030, 2037, 2038, 2039, 6137, 2047}, 8: {2050, 2051, 2053, 2054, 2057, 11, 4108, 14, 2062, 16, 2064, 2065, 2066, 2067, 2069, 2071, 23, 25, 28, 34, 35, 36, 2082, 2083, 39, 2085, 2087, 2089, 2090, 6180, 6191, 4144, 51, 6200, 4153, 6203, 2110, 6207, 4162, 2115, 2117, 2118, 2119, 4168, 4169, 74, 76, 4173, 2127, 2134, 6231, 6232, 2140, 2141, 2143, 2149, 103, 2152, 2153, 2154, 6248, 6251, 6252, 6254, 4207, 2160, 4209, 6260, 4220, 2180, 6278, 4234, 4235, 6284, 4237, 4239, 6289, 146, 147, 2194, 2199, 6296, 2206, 163, 168, 2222, 176, 6321, 2233, 6332, 2237, 6335, 192, 195, 2246, 2250, 6348, 2259, 2263, 4312, 6360, 218, 219, 4314, 4315, 6365, 6368, 6371, 4325, 4326, 4327, 6377, 236, 6381, 6383, 2290, 246, 2294, 6390, 2297, 2301, 6402, 6403, 262, 4359, 4363, 6411, 6415, 6418, 2324, 281, 2330, 4379, 285, 292, 6440, 2345, 2347, 2348, 299, 303, 2351, 4399, 4402, 6448, 2356, 312, 2361, 2362, 2363, 4412, 2365, 6461, 2385, 2388, 2393, 358, 2407, 2411, 2412, 4461, 2415, 368, 371, 2419, 2421, 2425, 391, 2439, 396, 398, 399, 2446, 2449, 2452, 4513, 2468, 421, 422, 423, 424, 2471, 427, 2480, 4530, 435, 2486, 2490, 2492, 449, 451, 4554, 4555, 460, 2510, 2519, 2529, 482, 508, 4607, 516, 4618, 4621, 526, 2580, 4638, 544, 2597, 550, 551, 560, 4657, 2613, 4663, 4664, 2617, 2632, 2633, 2635, 594, 2654, 2655, 4703, 620, 2674, 635, 4731, 2686, 4744, 4749, 655, 4760, 2715, 669, 4768, 673, 4773, 4779, 2738, 4786, 692, 4790, 4792, 4795, 705, 4802, 709, 2757, 711, 4806, 2763, 4811, 2765, 718, 2769, 4821, 2775, 728, 731, 732, 4830, 4834, 2788, 748, 4845, 752, 754, 2809, 2827, 2829, 2830, 786, 789, 791, 797, 2850, 4903, 815, 4911, 4915, 820, 826, 2874, 4927, 2884, 4932, 843, 849, 4952, 2905, 2907, 865, 4962, 2922, 876, 877, 2924, 4976, 2931, 4979, 2945, 900, 2949, 903, 2969, 2972, 2973, 927, 5025, 5027, 5031, 944, 5040, 5042, 5046, 5052, 5056, 3010, 5062, 5065, 3020, 986, 987, 3034, 3042, 995, 5091, 5092, 1002, 5107, 5109, 5128, 5133, 5137, 5154, 5165, 5169, 5173, 5176, 5178, 1090, 1093, 1097, 5201, 3170, 1123, 3171, 1143, 5240, 5241, 5245, 5253, 1158, 5255, 5263, 1174, 5270, 3224, 5271, 3232, 1197, 5304, 3268, 3269, 3270, 3271, 5317, 5335, 5352, 5358, 3312, 1266, 3317, 1282, 5380, 1296, 5395, 5412, 3366, 5418, 1325, 1328, 1330, 5428, 5438, 3393, 1350, 1353, 5449, 1357, 5464, 3418, 3425, 5476, 1386, 1387, 1388, 5485, 3438, 1394, 3444, 5494, 5497, 5498, 1408, 3460, 1414, 5512, 1437, 3485, 3491, 5539, 5542, 5550, 3512, 5562, 5568, 5570, 3531, 5583, 1491, 3553, 1509, 3561, 1523, 1532, 3587, 3588, 1541, 3590, 5641, 5648, 5659, 5670, 1582, 5683, 5684, 5689, 5698, 5703, 5705, 3670, 3675, 1632, 1633, 5728, 5732, 5733, 1638, 1642, 3691, 3698, 1652, 1655, 5751, 1657, 5756, 1662, 5758, 3722, 5771, 1678, 1681, 5781, 1686, 3738, 5786, 1693, 1695, 1702, 1705, 3754, 5802, 5806, 1716, 1717, 1721, 1726, 5822, 1736, 1737, 5832, 3796, 3799, 1753, 5850, 5853, 1766, 1770, 1771, 1772, 1773, 5869, 1776, 1780, 5876, 5883, 1788, 1791, 1792, 1797, 5895, 1808, 5907, 1821, 1825, 5923, 5925, 3881, 1836, 1837, 3884, 1839, 1840, 3886, 3895, 3896, 3901, 1854, 3905, 1862, 1863, 1866, 3914, 1868, 1870, 3922, 1875, 1880, 1884, 1885, 1886, 3937, 1892, 1893, 5999, 1904, 1908, 1909, 1911, 3962, 3967, 6016, 3970, 1926, 1927, 6023, 1930, 3982, 1936, 1937, 3984, 6036, 3999, 1956, 4005, 4010, 1965, 1966, 4014, 6066, 1971, 1972, 1973, 4022, 6068, 6075, 1980, 6079, 4032, 1986, 4035, 6082, 4037, 6084, 4039, 1993, 1994, 1995, 4045, 4046, 2000, 2002, 6102, 2010, 4062, 4063, 6111, 4069, 4072, 2028, 6124, 2036, 6136, 2041, 4091, 2046}, 9: {1537, 2, 3586, 1540, 3588, 5641, 3596, 1551, 4626, 4627, 4628, 3616, 37, 38, 39, 1534, 1579, 45, 46, 1069, 48, 49, 50, 1071, 1072, 53, 1078, 1079, 1591, 1592, 58, 1084, 3644, 1086, 1087, 1088, 65, 1091, 1092, 3651, 72, 3658, 75, 1101, 79, 80, 3686, 3695, 2675, 1141, 1142, 1654, 1144, 3702, 2171, 1147, 124, 1149, 1150, 1152, 3711, 130, 131, 1156, 133, 1158, 1159, 1160, 1161, 1162, 3719, 1673, 1165, 1166, 1167, 3726, 1174, 5629, 2722, 3747, 2731, 2225, 3762, 4280, 1220, 1222, 4295, 1228, 1229, 1230, 1231, 1234, 3794, 1237, 1749, 1239, 3803, 1762, 3811, 1252, 2796, 3820, 4339, 3828, 3844, 4367, 1296, 2320, 3859, 1300, 4373, 1303, 5405, 5406, 1312, 4384, 1317, 1319, 1320, 1321, 1322, 1323, 1328, 1330, 823, 831, 833, 835, 838, 843, 845, 850, 851, 3630, 857, 859, 860, 863, 864, 865, 866, 868, 1383, 874, 1386, 878, 879, 880, 881, 1390, 883, 1395, 1401, 1403, 893, 894, 382, 896, 1406, 1407, 1413, 902, 395, 908, 909, 3468, 911, 912, 2451, 916, 918, 4502, 922, 411, 412, 925, 3485, 927, 3487, 417, 932, 934, 944, 946, 947, 1460, 5554, 1462, 951, 952, 1463, 1465, 1466, 1467, 957, 958, 959, 960, 961, 962, 1471, 964, 1473, 3520, 1479, 1486, 1487, 1488, 977, 978, 979, 980, 1489, 986, 4573, 991, 992, 994, 3557, 1000, 1517, 495, 1008, 1521, 1522, 3569, 1012, 1529, 1530, 1019, 1017, 5630, 1535}, 10: {2, 28, 37, 39, 42, 43, 46, 47, 48, 50, 53, 59, 60, 65, 72, 75, 76, 80, 81, 124, 125, 126, 127, 130, 132, 133, 4234, 4251, 6329, 4301, 4334, 245, 4367, 4391, 6449, 4459, 4464, 4484, 2451, 404, 4502, 412, 414, 4526, 4550, 4573, 491, 495, 519, 4628, 4630, 680, 4797, 2765, 2795, 4868, 823, 828, 829, 832, 833, 834, 838, 840, 843, 845, 846, 847, 850, 851, 853, 854, 857, 858, 859, 860, 862, 864, 867, 869, 872, 873, 874, 879, 880, 883, 887, 888, 889, 890, 891, 893, 895, 896, 897, 901, 902, 903, 904, 907, 908, 909, 911, 915, 916, 917, 918, 919, 921, 922, 925, 926, 927, 931, 933, 934, 936, 5037, 944, 945, 949, 950, 958, 959, 962, 963, 964, 968, 972, 976, 978, 979, 984, 986, 988, 993, 994, 5093, 1000, 1001, 1002, 5097, 1008, 1009, 1012, 1013, 1016, 1017, 1018, 1019, 5160, 5161, 1069, 1071, 1073, 1074, 1077, 1078, 5174, 1080, 1081, 1082, 1083, 5175, 1085, 1088, 1089, 1092, 1093, 1094, 1098, 1099, 5202, 5205, 1141, 1144, 1146, 1147, 1148, 1149, 1150, 1151, 1157, 1158, 1159, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1170, 1171, 1174, 1175, 5299, 1220, 1221, 1223, 1224, 1226, 1227, 1228, 1229, 1230, 1233, 1234, 1236, 1237, 1240, 1242, 1244, 1248, 1249, 1252, 1297, 1299, 1301, 1302, 1303, 1306, 1308, 1312, 1313, 1316, 1317, 1319, 1320, 1323, 1325, 1327, 1328, 1329, 1330, 1332, 5452, 1378, 1380, 1388, 1389, 1390, 1393, 1395, 1397, 1398, 1401, 1403, 1404, 1407, 1408, 1409, 5508, 1412, 3470, 3473, 3476, 3478, 3485, 3489, 3506, 1460, 1461, 1462, 1463, 1465, 1466, 3516, 1468, 1469, 1470, 5567, 1473, 1475, 1476, 1477, 3526, 1479, 1478, 1481, 1483, 1485, 1487, 1488, 1489, 1490, 3537, 3542, 3547, 3551, 3553, 3554, 3557, 3559, 1517, 1519, 1520, 3569, 1522, 1521, 1524, 1526, 3576, 1529, 1530, 1531, 1532, 1533, 3581, 1535, 1536, 1537, 1538, 1539, 1540, 5637, 1543, 1545, 1546, 3595, 1550, 1551, 3601, 3606, 3607, 3610, 3611, 5672, 1579, 1580, 1581, 3630, 1586, 3644, 3651, 3661, 3667, 3673, 1631, 3687, 3700, 1654, 3702, 5762, 3720, 3731, 3745, 3748, 1710, 3758, 1713, 3766, 3770, 3771, 3773, 3794, 3807, 3811, 3817, 3832, 3838, 3842, 3865, 3876, 1853, 4034, 6083}, 11: {2, 69, 76, 80, 127, 2210, 171, 2234, 2244, 4301, 211, 6357, 232, 4344, 2300, 257, 2308, 4377, 6438, 4400, 4404, 309, 2397, 373, 374, 375, 376, 4473, 377, 380, 381, 382, 4478, 384, 383, 386, 387, 388, 389, 391, 393, 395, 396, 397, 400, 402, 404, 2452, 406, 40

In [13]:
def check_label(row):
    q_id = row['query_id']
    job_id = row['id']
    # Lấy tập hợp các job đúng của query này từ Ground Truth
    true_jobs = ground_truth.get(q_id, set())
    # Nếu job_id này nằm trong tập đúng -> 1, ngược lại -> 0
    return 1 if int(job_id) in true_jobs else 0

# Tạo cột label mới chuẩn xác 100%
dev['label'] = dev.apply(check_label, axis=1)

In [14]:
dev.head()

         model  query_id  rank     score    id  label
0  tfidf basic         0     1  0.434380  2453      1
1  tfidf basic         0     2  0.424796  2311      1
2  tfidf basic         0     3  0.399933  2281      1
3  tfidf basic         0     4  0.331504  4571      0
4  tfidf basic         0     5  0.306119   746      0

In [51]:
dev.to_excel('eval_with_gt_min2.xlsx', index=False)

In [ ]:
import pandas as pd
dev = pd.read_excel('eval_with_gt_min2.xlsx')
dev.head()

,model_short,model_type,query_id,query_text,rank,job_id,score,label,id,title,description,requirements,benefit,type,location,position,salary_range,specializations,min_salary_edited,max_salary_edited,currency_salary,overall_text,title_processed,overall_text_processed
0,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,1,2453,0.434380,0.0,2453,Tuyển Backend Developer Python làm việc tại Cô...,"[""Thiết kế và phát triển các module backend độ...","[""2 năm kinh nghiệm backend Python trở lên., T...","[""Thu nhập hấp dẫn, nhiều cơ hội học hỏi., Cun...",Toàn thời gian,Hà Nội,Nhân viên,Thoả thuận,"['Backend Developer', 'IT - Phần mềm']",0.0,0.0,Unknown,Tuyển Backend Developer Python làm việc tại Cô...,tuyển backend developer python làm_việc công_t...,tuyển backend developer python làm_việc công_t...
1,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,2,2311,0.424796,0.0,2311,Tuyển Senior Backend Developer (Python) làm vi...,"[""We are seeking a Senior Backend Engineer (Py...","[""5+ years of professional experience in backe...","[""Competitive salary commensurate with experie...",Toàn thời gian,Hà Nội,Nhân viên,28 - 35 triệu,"['Backend Developer', 'IT - Phần mềm']",28.0,35.0,triệu VND,Tuyển Senior Backend Developer (Python) làm vi...,tuyển senior backend developer python làm_việc...,tuyển senior backend developer python làm_việc...
2,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,3,2281,0.399933,0.0,2281,Tuyển Backend Developer (Python) làm việc tại ...,"[""Develop and implement algorithms to handle m...","[""4++ years of experience in backend programmi...","[""Hybrid working model: Enjoy the flexibility ...",Toàn thời gian,Hà Nội,Trưởng nhóm,Tới 55 triệu,"['Software Engineer', 'IT - Phần mềm']",0.0,55.0,triệu VND,Tuyển Backend Developer (Python) làm việc tại ...,tuyển backend developer python làm_việc công_t...,tuyển backend developer python làm_việc công_t...
3,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,4,4571,0.331504,1.0,4571,Tuyển Thực Tập Sinh Kinh Doanh làm việc tại Cô...,"[""Tiếp nhận các kế hoạch triển khai kinh doanh...","[""Không yêu cầu kinh nghiệm, chưa có sẽ được đ...","[""Thu nhập: 4 - 6 triệu VND, Lương cứng: Đến...",Toàn thời gian,Đà Nẵng,Nhân viên,"Thu nhập, 4 - 6 triệu","['Sales bất động sản/Môi giới bất động sản', '...",4.0,6.0,triệu VND,Tuyển Thực Tập Sinh Kinh Doanh làm việc tại Cô...,tuyển thực_tập sinh kinh_doanh làm_việc công_t...,tuyển thực_tập sinh kinh_doanh làm_việc công_t...
4,tfidf,basic,0,Thực tập sinh IT Python Backend không yêu cầu ...,5,746,0.306119,0.0,746,Tuyển Python Developer làm việc tại Công ty Cổ...,"[""Design, develop, and maintain software appli...","[""Bachelor’s degree in computer science, Softw...","[""Probation salary is 100% of official salary ...",Toàn thời gian,Hà Nội,Nhân viên,20 - 25 triệu,"['Software Engineer', 'IT - Phần mềm']",20.0,25.0,triệu VND,Tuyển Python Developer làm việc tại Công ty Cổ...,tuyển python developer làm_việc công_ty cổ_phầ...,tuyển python developer làm_việc công_ty cổ_phầ...

In [15]:
import pandas as pd
import numpy as np

def calculate_metrics_optimized(group):
    # Lấy thông tin index
    if isinstance(group.name, tuple):
        model_name, q_id = group.name
    else:
        q_id = group.name
    
    # 1. Sắp xếp và lấy label
    group = group.sort_values('rank')
    relevants = group['label'].values 
    
    # 2. Lấy mẫu số (Ground Truth)
    # LƯU Ý QUAN TRỌNG: ground_truth phải là dict chứa set các ID đúng
    true_set = ground_truth.get(q_id, set())
    total_true_items = len(true_set)
    
    metrics = {}
    
    # --- Pre-calculation ---
    ranks = np.arange(len(relevants)) + 1
    cumulative_relevant = np.cumsum(relevants)
    precisions_at_i = cumulative_relevant / ranks
    discounts = np.log2(ranks + 1)
    
    # ====================================================
    # A. GLOBAL METRICS
    # ====================================================
    # MAP: Đúng (Đã chia cho total_true_items)
    if total_true_items > 0:
        metrics['MAP'] = np.sum(precisions_at_i * relevants) / total_true_items
    else:
        metrics['MAP'] = 0

    # MRR: Đúng (Không phụ thuộc số lượng true items, chỉ cần vị trí đầu tiên)
    try:
        first_rel_idx = np.argmax(relevants == 1)
        if relevants[first_rel_idx] == 1:
            metrics['MRR'] = 1 / (first_rel_idx + 1)
        else:
            metrics['MRR'] = 0
    except:
        metrics['MRR'] = 0

    # ====================================================
    # B. METRICS TẠI CÁC NGƯỠNG K
    # ====================================================
    cutoffs = [5, 10, 20]
    
    for k in cutoffs:
        actual_k = min(k, len(relevants))
        r_k = relevants[:actual_k]
        
        # 1. Hit Ratio@K (Đúng)
        metrics[f'Hit@{k}'] = 1 if np.any(r_k) else 0
        
        # 2. Precision@K (Đúng - chia cho K)
        metrics[f'P@{k}'] = cumulative_relevant[actual_k - 1] / k if actual_k > 0 else 0
        
        # 3. NDCG@K (ĐÃ SỬA LẠI LOGIC IDCG)
        # ---------------------------------------------------------
        dcg = np.sum(r_k / discounts[:actual_k])
        
        # Logic IDCG chuẩn:
        # Tạo một vector lý tưởng có độ dài bằng actual_k
        # Điền số 1 vào vector này dựa trên số lượng ground truth có sẵn
        ideal_r_k = np.zeros(actual_k)
        
        # Số lượng item đúng tối đa có thể nhét vào Top K này
        # Là min của (K đang xét, Tổng số item đúng thực tế)
        num_ones_possible = min(actual_k, total_true_items)
        
        ideal_r_k[:num_ones_possible] = 1 # Gán các vị trí đầu tiên bằng 1
        
        idcg = np.sum(ideal_r_k / discounts[:actual_k])
        
        metrics[f'NDCG@{k}'] = dcg / idcg if idcg > 0 else 0
        # ---------------------------------------------------------
        
        # 4. MRR@K (Đúng)
        first_idx_k = np.argmax(r_k == 1)
        if r_k[first_idx_k] == 1:
            metrics[f'MRR@{k}'] = 1 / (first_idx_k + 1)
        else:
            metrics[f'MRR@{k}'] = 0
            
        # 5. MAP@K (Đúng - Đã chia cho total_true_items)
        if total_true_items > 0:
            p_k = precisions_at_i[:actual_k]
            metrics[f'MAP@{k}'] = np.sum(p_k * r_k) / total_true_items
        else:
            metrics[f'MAP@{k}'] = 0

    return pd.Series(metrics)

In [17]:
final_report = dev.groupby(['model', 'query_id']).apply(calculate_metrics_optimized).reset_index()
metric_cols = [c for c in final_report.columns if c not in ['model', 'query_id']]

summary = final_report.groupby('model')[metric_cols].mean()
print(summary)

                           MAP       MRR  Hit@5   P@5    NDCG@5     MRR@5  \
model
bge basic             0.071718  0.916667   1.00  0.72  0.750804  0.916667
bge upgrade           0.086943  0.890000   0.95  0.73  0.760629  0.885000
doc2vec basic         0.016039  0.541071   0.75  0.36  0.361442  0.529167
doc2vec upgrade       0.002401  0.153472   0.20  0.08  0.086879  0.141667
doc2vec_dbow basic    0.022367  0.708889   0.75  0.48  0.510830  0.700000
doc2vec_dbow upgrade  0.042532  0.721667   0.95  0.55  0.563160  0.716667
ensemble basic        0.081972  0.900000   1.00  0.79  0.800232  0.900000
ensemble upgrade      0.105614  0.912143   0.90  0.74  0.780983  0.900000
labse basic           0.079144  0.835000   1.00  0.68  0.700472  0.835000
labse upgrade         0.084169  0.826667   1.00  0.77  0.763663  0.826667
mpnet basic           0.048085  0.594167   0.80  0.42  0.427456  0.572500
mpnet upgrade         0.056828  0.522143   0.80  0.47  0.447006  0.499167
tfidf basic           0.075000  0.883333   1.00  0.78  0.787010  0.883333
tfidf upgrade         0.094254  0.795833   0.90  0.72  0.722142  0.779167
w2v basic             0.000491  0.070441   0.10  0.05  0.042566  0.050000
w2v upgrade           0.002437  0.202143   0.30  0.13  0.132299  0.195000
w2v_sg basic          0.018888  0.575657   0.75  0.41  0.418234  0.551667
w2v_sg upgrade        0.001084  0.098310   0.15  0.03  0.030822  0.072500

                         MAP@5  Hit@10   P@10   NDCG@10    MRR@10    MAP@10  \
model
bge basic             0.031743    1.00  0.620  0.669937  0.916667  0.049515
bge upgrade           0.037204    1.00  0.670  0.707775  0.890000  0.059504
doc2vec basic         0.009819    0.75  0.325  0.335533  0.529167  0.012620
doc2vec upgrade       0.000760    0.30  0.095  0.094722  0.153472  0.001119
doc2vec_dbow basic    0.009730    0.80  0.435  0.467393  0.705556  0.013140
doc2vec_dbow upgrade  0.020814    1.00  0.510  0.530403  0.721667  0.029300
ensemble basic        0.037275    1.00  0.675  0.717529  0.900000  0.058626
ensemble upgrade      0.039332    1.00  0.750  0.771689  0.912143  0.071766
labse basic           0.035420    1.00  0.650  0.672536  0.835000  0.054105
labse upgrade         0.032532    1.00  0.725  0.733446  0.826667  0.057008
mpnet basic           0.017261    0.95  0.430  0.433229  0.591389  0.028970
mpnet upgrade         0.021101    0.90  0.495  0.474124  0.514643  0.036195
tfidf basic           0.034240    1.00  0.710  0.737814  0.883333  0.055876
tfidf upgrade         0.034579    1.00  0.695  0.704233  0.795833  0.057791
w2v basic             0.000188    0.25  0.050  0.044979  0.067500  0.000277
w2v upgrade           0.001002    0.35  0.105  0.114663  0.202143  0.001430
w2v_sg basic          0.008033    0.90  0.400  0.409998  0.571111  0.013385
w2v_sg upgrade        0.000362    0.30  0.045  0.041382  0.090893  0.000746

                      Hit@20    P@20   NDCG@20    MRR@20    MAP@20
model
bge basic               1.00  0.5450  0.600539  0.916667  0.071718
bge upgrade             1.00  0.6200  0.660685  0.890000  0.086943
doc2vec basic           0.90  0.2850  0.305264  0.541071  0.016039
doc2vec upgrade         0.30  0.1125  0.107260  0.153472  0.002401
doc2vec_dbow basic      0.85  0.4200  0.445493  0.708889  0.022367
doc2vec_dbow upgrade    1.00  0.4975  0.515271  0.721667  0.042532
ensemble basic          1.00  0.6025  0.652522  0.900000  0.081972
ensemble upgrade        1.00  0.6725  0.711955  0.912143  0.105614
labse basic             1.00  0.5700  0.609572  0.835000  0.079144
labse upgrade           1.00  0.6325  0.666384  0.826667  0.084169
mpnet basic             1.00  0.4300  0.433969  0.594167  0.048085
mpnet upgrade           1.00  0.4675  0.464170  0.522143  0.056828
tfidf basic             1.00  0.6025  0.654266  0.883333  0.075000
tfidf upgrade           1.00  0.6850  0.696774  0.795833  0.094254
w2v basic               0.30  0.0550  0.050273  0.070441  0.000491
w2v upgrade             0.35  0.0950  0.103889  0.202143  0.002437
w2v_sg basic            0.95  0.3825  0.394195  0.575657  0.018888
w2v_sg upgrade          0.40  0.0500  0.046454  0.098310  0.001084

In [18]:
summary.to_excel('eval_min2_final2.xlsx')

In [8]:
import pandas as pd
import numpy as np

def calculate_metrics_optimized(group):
    # Lấy thông tin index
    if isinstance(group.name, tuple):
        model_name, q_id = group.name
    else:
        q_id = group.name
    
    # 1. Sắp xếp và lấy label
    # Giả sử group này chứa tối đa N dòng (ví dụ N=20)
    group = group.sort_values('rank')
    relevants = group['label'].values 
    
    # 2. Lấy mẫu số (Ground Truth)
    true_set = ground_truth.get(q_id, set())
    total_true_items = len(true_set)
    
    metrics = {}
    
    # ====================================================
    # TÍNH TOÁN CÁC MẢNG CƠ SỞ (Pre-calculation)
    # Bước này tính 1 lần dùng cho cả Global và các Cutoff K
    # ====================================================
    
    # Mảng Rank: [1, 2, 3, ..., N]
    ranks = np.arange(len(relevants)) + 1
    
    # Mảng Precision tại mọi vị trí: [P@1, P@2, ..., P@N]
    # cumsum: số lượng đúng tích lũy
    cumulative_relevant = np.cumsum(relevants)
    precisions_at_i = cumulative_relevant / ranks
    
    # Mảng Discount cho NDCG: log2(i+2)
    discounts = np.log2(ranks + 1)
    
    # ====================================================
    # A. GLOBAL METRICS (Tương đương @MAX_LENGTH)
    # ====================================================
    if total_true_items > 0:
        # MAP = Tổng(Precision[i] * rel[i]) / Tổng số văn bản đúng
        metrics['MAP'] = np.sum(precisions_at_i * relevants) / total_true_items
    else:
        metrics['MAP'] = 0

    # MRR Global
    try:
        first_rel_idx = np.argmax(relevants == 1)
        if relevants[first_rel_idx] == 1:
            metrics['MRR'] = 1 / (first_rel_idx + 1)
        else:
            metrics['MRR'] = 0
    except:
        metrics['MRR'] = 0

    # ====================================================
    # B. METRICS TẠI CÁC NGƯỠNG K (CUTOFFS)
    # ====================================================
    cutoffs = [5, 10, 20]
    
    for k in cutoffs:
        # Nếu k lớn hơn độ dài list thì lấy max độ dài list
        actual_k = min(k, len(relevants))
        
        # Cắt mảng (Slicing) - Không cần tính lại từ đầu
        r_k = relevants[:actual_k]
        
        # 1. Hit Ratio@K
        # Kiểm tra xem có số 1 nào trong mảng r_k không
        metrics[f'Hit@{k}'] = 1 if np.any(r_k) else 0
        
        # 2. Precision@K
        # Dùng giá trị cuối cùng của mảng cumulative đã cắt (nhanh hơn sum lại)
        metrics[f'P@{k}'] = cumulative_relevant[actual_k - 1] / k if actual_k > 0 else 0
        
        # 3. NDCG@K
        dcg = np.sum(r_k / discounts[:actual_k])
        
        # IDCG (Cách tính của bạn: Sắp xếp lại r_k để 1 lên đầu)
        ideal_r_k = sorted(r_k, reverse=True)
        idcg = np.sum(ideal_r_k / discounts[:actual_k])
        
        metrics[f'NDCG@{k}'] = dcg / idcg if idcg > 0 else 0
        
        # 4. MRR@K
        # Tìm index đầu tiên bằng 1 trong phạm vi k
        # argmax trên mảng cắt r_k
        first_idx_k = np.argmax(r_k == 1)
        if r_k[first_idx_k] == 1:
            metrics[f'MRR@{k}'] = 1 / (first_idx_k + 1)
        else:
            metrics[f'MRR@{k}'] = 0
            
        # 5. MAP@K
        # MAP@K chỉ tính tổng precision trong top K chia cho tổng số Ground Truth
        if total_true_items > 0:
            # Lấy mảng precision đã tính sẵn, cắt đến k
            p_k = precisions_at_i[:actual_k]
            # Nhân với r_k để chỉ cộng những vị trí relevant
            metrics[f'MAP@{k}'] = np.sum(p_k * r_k) / total_true_items
        else:
            metrics[f'MAP@{k}'] = 0

    return pd.Series(metrics)

In [9]:
final_report = dev.groupby(['model', 'query_id']).apply(calculate_metrics_complete).reset_index()
metric_cols = [c for c in final_report.columns if c not in ['model', 'query_id']]

summary = final_report.groupby('model')[metric_cols].mean()
print(summary)

                           MAP       MRR  Hit@5   P@5    NDCG@5     MRR@5  \
model
bge basic             0.071718  0.916667   1.00  0.72  0.784811  0.916667
bge upgrade           0.086943  0.890000   0.95  0.73  0.766810  0.885000
doc2vec basic         0.016039  0.541071   0.75  0.36  0.406239  0.529167
doc2vec upgrade       0.002401  0.153472   0.20  0.08  0.090132  0.141667
doc2vec_dbow basic    0.022367  0.708889   0.75  0.48  0.538340  0.700000
doc2vec_dbow upgrade  0.042532  0.721667   0.95  0.55  0.604377  0.716667
ensemble basic        0.081972  0.900000   1.00  0.79  0.800232  0.900000
ensemble upgrade      0.105614  0.912143   0.90  0.74  0.785160  0.900000
labse basic           0.079144  0.835000   1.00  0.68  0.715787  0.835000
labse upgrade         0.084169  0.826667   1.00  0.77  0.768943  0.826667
mpnet basic           0.048085  0.594167   0.80  0.42  0.461258  0.572500
mpnet upgrade         0.056828  0.522143   0.80  0.47  0.465549  0.499167
tfidf basic           0.075000  0.883333   1.00  0.78  0.787010  0.883333
tfidf upgrade         0.094254  0.795833   0.90  0.72  0.724944  0.779167
w2v basic             0.000491  0.070441   0.10  0.05  0.042566  0.050000
w2v upgrade           0.002437  0.202143   0.30  0.13  0.173157  0.195000
w2v_sg basic          0.018888  0.575657   0.75  0.41  0.479070  0.551667
w2v_sg upgrade        0.001084  0.098310   0.15  0.03  0.044218  0.072500

                         MAP@5  Hit@10   P@10   NDCG@10    MRR@10    MAP@10  \
model
bge basic             0.031743    1.00  0.620  0.777256  0.916667  0.049515
bge upgrade           0.037204    1.00  0.670  0.751878  0.890000  0.059504
doc2vec basic         0.009819    0.75  0.325  0.434904  0.529167  0.012620
doc2vec upgrade       0.000760    0.30  0.095  0.116647  0.153472  0.001119
doc2vec_dbow basic    0.009730    0.80  0.435  0.554001  0.705556  0.013140
doc2vec_dbow upgrade  0.020814    1.00  0.510  0.636548  0.721667  0.029300
ensemble basic        0.037275    1.00  0.675  0.781790  0.900000  0.058626
ensemble upgrade      0.039332    1.00  0.750  0.807284  0.912143  0.071766
labse basic           0.035420    1.00  0.650  0.738799  0.835000  0.054105
labse upgrade         0.032532    1.00  0.725  0.777791  0.826667  0.057008
mpnet basic           0.017261    0.95  0.430  0.537446  0.591389  0.028970
mpnet upgrade         0.021101    0.90  0.495  0.548550  0.514643  0.036195
tfidf basic           0.034240    1.00  0.710  0.801592  0.883333  0.055876
tfidf upgrade         0.034579    1.00  0.695  0.727661  0.795833  0.057791
w2v basic             0.000188    0.25  0.050  0.076490  0.067500  0.000277
w2v upgrade           0.001002    0.35  0.105  0.187495  0.202143  0.001430
w2v_sg basic          0.008033    0.90  0.400  0.554447  0.571111  0.013385
w2v_sg upgrade        0.000362    0.30  0.045  0.096001  0.090893  0.000746

                      Hit@20    P@20   NDCG@20    MRR@20    MAP@20
model
bge basic               1.00  0.5450  0.884215  0.916667  0.071718
bge upgrade             1.00  0.6200  0.870801  0.890000  0.086943
doc2vec basic           0.90  0.2850  0.595908  0.541071  0.016039
doc2vec upgrade         0.30  0.1125  0.191183  0.153472  0.002401
doc2vec_dbow basic      0.85  0.4200  0.675859  0.708889  0.022367
doc2vec_dbow upgrade    1.00  0.4975  0.793028  0.721667  0.042532
ensemble basic          1.00  0.6025  0.895506  0.900000  0.081972
ensemble upgrade        1.00  0.6725  0.895417  0.912143  0.105614
labse basic             1.00  0.5700  0.863088  0.835000  0.079144
labse upgrade           1.00  0.6325  0.872099  0.826667  0.084169
mpnet basic             1.00  0.4300  0.697203  0.594167  0.048085
mpnet upgrade           1.00  0.4675  0.695158  0.522143  0.056828
tfidf basic             1.00  0.6025  0.898584  0.883333  0.075000
tfidf upgrade           1.00  0.6850  0.857081  0.795833  0.094254
w2v basic               0.30  0.0550  0.135668  0.070441  0.000491
w2v upgrade             0.35  0.0950  0.234243  0.202143  0.002437
w2v_sg basic            0.95  0.3825  0.674755  0.575657  0.018888
w2v_sg upgrade          0.40  0.0500  0.168944  0.098310  0.001084

In [10]:
summary.to_excel('eval_min2_final.xlsx')

In [ ]:
import numpy as np
job_title_bge_m3_basic = np.load('../job_title_embeddings_bge_m3_vn_basic.npy')
job_text_bge_m3_upgrade = np.load('../job_text_embeddings_bge_m3_vn_upgrade.npy')
job_title_doc2vec_basic = np.load('../job_title_embeddings_doc2vec_vn_basic.npy')
job_text_doc2vec_upgrade = np.load('../job_text_embeddings_doc2vec_vn_upgrade.npy')
job_title_doc2vec_basic_dbow = np.load('../job_title_embeddings_doc2vec_vn_basic_dbow.npy')
job_text_doc2vec_upgrade_dbow = np.load('../job_text_embeddings_doc2vec_vn_upgrade_dbow.npy')
job_title_w2v_basic = np.load('../job_title_embeddings_w2v_ave_vn_basic.npy')
job_text_w2v_upgrade = np.load('../job_text_embeddings_w2v_ave_vn_upgrade.npy')
job_title_w2v_basic_sg = np.load('../job_title_embeddings_w2v_ave_vn_basic_sg.npy')
job_text_w2v_upgrade_sg = np.load('../job_text_embeddings_w2v_ave_vn_upgrade_sg.npy')
job_title_labse_basic = np.load('../job_title_embeddings_labse_vn_basic.npy')
job_text_labse_upgrade = np.load('../job_text_embeddings_labse_vn_upgrade.npy')
job_title_mpnet_basic = np.load('../job_title_embeddings_mpnet_vn_basic.npy')
job_text_mpnet_upgrade = np.load('../job_text_embeddings_mpnet_vn_upgrade.npy')

print("Loaded embeddings shapes:")
print("BGE-M3 Basic Title:", job_title_bge_m3_basic.shape)
print("BGE-M3 Upgrade Text:", job_text_bge_m3_upgrade.shape)
print("Doc2Vec Basic Title:", job_title_doc2vec_basic.shape)
print("Doc2Vec Upgrade Text:", job_text_doc2vec_upgrade.shape)
print("Doc2Vec DBOW Basic Title:", job_title_doc2vec_basic_dbow.shape)
print("Doc2Vec DBOW Upgrade Text:", job_text_doc2vec_upgrade_dbow.shape)
print("Word2Vec Basic Title:", job_title_w2v_basic.shape)
print("Word2Vec Upgrade Text:", job_text_w2v_upgrade.shape)
print("Word2Vec SG Basic Title:", job_title_w2v_basic_sg.shape)
print("Word2Vec SG Upgrade Text:", job_text_w2v_upgrade_sg.shape)
print("LaBSE Basic Title:", job_title_labse_basic.shape)
print("LaBSE Upgrade Text:", job_text_labse_upgrade.shape)
print("MPNet Basic Title:", job_title_mpnet_basic.shape)
print("MPNet Upgrade Text:", job_text_mpnet_upgrade.shape)

Loaded embeddings shapes:
BGE-M3 Basic Title: (6473, 1024)
BGE-M3 Upgrade Text: (6473, 1024)
Doc2Vec Basic Title: (6473, 100)
Doc2Vec Upgrade Text: (6473, 100)
Doc2Vec DBOW Basic Title: (6473, 100)
Doc2Vec DBOW Upgrade Text: (6473, 100)
Word2Vec Basic Title: (6473, 100)
Word2Vec Upgrade Text: (6473, 100)
Word2Vec SG Basic Title: (6473, 100)
Word2Vec SG Upgrade Text: (6473, 100)
LaBSE Basic Title: (6473, 768)
LaBSE Upgrade Text: (6473, 768)
MPNet Basic Title: (6473, 768)
MPNet Upgrade Text: (6473, 768)

 (6473, 1024)